"""
Dua Library Seed Data — 104 duas across 12 categories
======================================================
All duas sourced from authentic collections (Bukhari, Muslim, Abu Dawud, etc.)
"""

DUA_SEED_DATA = [
    # ─── Morning / Evening Adhkar ─────────────────────────────────────────────
    {"key": "morning_waking",         "category": "morning_evening", "dua_order": 1,
     "title": "Upon waking",
     "arabic_text": "الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ",
     "transliteration": "Alhamdu lillahil-ladhi ahyana ba'da ma amatana wa ilayhin-nushoor",
     "translation": "All praise is for Allah who gave us life after having taken it from us and unto Him is the resurrection.",
     "source": "Bukhari 6312", "repetition_count": 1, "when_to_recite": "Upon waking from sleep"},
    {"key": "morning_supplication",   "category": "morning_evening", "dua_order": 2,
     "title": "Morning supplication",
     "arabic_text": "اللَّهُمَّ بِكَ أَصْبَحْنَا وَبِكَ أَمْسَيْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ النُّشُورُ",
     "transliteration": "Allahumma bika asbahna wa bika amsayna wa bika nahya wa bika namootu wa ilaykan-nushoor",
     "translation": "O Allah, by You we reach the morning, by You we reach the evening, by You we live and by You we die, and to You is the resurrection.",
     "source": "Abu Dawud 5068", "repetition_count": 1, "when_to_recite": "Morning"},
    {"key": "evening_supplication",   "category": "morning_evening", "dua_order": 3,
     "title": "Evening supplication",
     "arabic_text": "اللَّهُمَّ بِكَ أَمْسَيْنَا وَبِكَ أَصْبَحْنَا وَبِكَ نَحْيَا وَبِكَ نَمُوتُ وَإِلَيْكَ الْمَصِيرُ",
     "transliteration": "Allahumma bika amsayna wa bika asbahna wa bika nahya wa bika namootu wa ilaykal-maseer",
     "translation": "O Allah, by You we reach the evening, by You we reach the morning, by You we live and by You we die, and to You is the return.",
     "source": "Abu Dawud 5068", "repetition_count": 1, "when_to_recite": "Evening"},
    {"key": "ayat_al_kursi",          "category": "morning_evening", "dua_order": 4,
     "title": "Ayat al-Kursi",
     "arabic_text": "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ",
     "transliteration": "Allahu la ilaha illa huwal-hayyul-qayyoom, la ta'khudhuhu sinatun wa la nawm",
     "translation": "Allah — there is no deity except Him, the Ever-Living, the Sustainer of existence. Neither drowsiness overtakes Him nor sleep.",
     "source": "Quran 2:255", "repetition_count": 1, "when_to_recite": "After every obligatory prayer and before sleep"},
    {"key": "morning_protection",     "category": "morning_evening", "dua_order": 5,
     "title": "Morning protection dua",
     "arabic_text": "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ فِي الدُّنْيَا وَالآخِرَةِ",
     "transliteration": "Allahumma inni as'alukal-'afiyata fid-dunya wal-akhirah",
     "translation": "O Allah, I ask You for well-being in this world and the Hereafter.",
     "source": "Ibn Majah 3871", "repetition_count": 1, "when_to_recite": "Morning"},
    {"key": "subhanallah_morning",    "category": "morning_evening", "dua_order": 6,
     "title": "SubhanAllah 100x",
     "arabic_text": "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ",
     "transliteration": "SubhanAllahi wa bihamdih",
     "translation": "Glory be to Allah and praise be to Him.",
     "source": "Bukhari 6405, Muslim 2691", "repetition_count": 100,
     "when_to_recite": "Morning and evening — whoever says it 100 times will have his sins forgiven even if they are like the foam of the sea"},
    {"key": "sayyid_al_istighfar",   "category": "morning_evening", "dua_order": 7,
     "title": "Sayyid al-Istighfar (Master of Forgiveness)",
     "arabic_text": "اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ",
     "transliteration": "Allahumma anta Rabbi la ilaha illa ant, khalaqtani wa ana 'abduk, wa ana 'ala 'ahdika wa wa'dika mastata't",
     "translation": "O Allah, You are my Lord. There is no god but You. You created me and I am Your slave. I am upon Your covenant and promise as best I can.",
     "source": "Bukhari 6306", "repetition_count": 1,
     "when_to_recite": "Morning — whoever says it with conviction in the morning and dies that day will be from the people of Paradise"},
    {"key": "morning_three_quls",    "category": "morning_evening", "dua_order": 8,
     "title": "Three Quls (Al-Ikhlas, Al-Falaq, An-Nas)",
     "arabic_text": "قُلْ هُوَ اللَّهُ أَحَدٌ ... قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ... قُلْ أَعُوذُ بِرَبِّ النَّاسِ",
     "transliteration": "Qul huwa Allahu ahad... Qul a'udhu bi rabbil-falaq... Qul a'udhu bi rabbin-nas",
     "translation": "Recite Surah Al-Ikhlas, Al-Falaq, and An-Nas.",
     "source": "Abu Dawud 5082, Tirmidhi 3575", "repetition_count": 3,
     "when_to_recite": "Morning, evening, and before sleep — 3 times each"},

    # ─── After Prayer ─────────────────────────────────────────────────────────
    {"key": "after_prayer_istighfar",  "category": "after_prayer", "dua_order": 1,
     "title": "Seeking forgiveness after prayer",
     "arabic_text": "أَسْتَغْفِرُ اللَّهَ",
     "transliteration": "Astaghfirullah",
     "translation": "I seek forgiveness from Allah.",
     "source": "Muslim 591", "repetition_count": 3, "when_to_recite": "Immediately after salam in salah"},
    {"key": "after_prayer_subhanallah", "category": "after_prayer", "dua_order": 2,
     "title": "SubhanAllah, Alhamdulillah, Allahu Akbar",
     "arabic_text": "سُبْحَانَ اللَّهِ ... الْحَمْدُ لِلَّهِ ... اللَّهُ أَكْبَرُ",
     "transliteration": "SubhanAllah (33x), Alhamdulillah (33x), Allahu Akbar (33x)",
     "translation": "Glory be to Allah (33x), All praise be to Allah (33x), Allah is the Greatest (33x).",
     "source": "Muslim 597", "repetition_count": 33, "when_to_recite": "After every obligatory prayer"},
    {"key": "after_prayer_la_ilaha",  "category": "after_prayer", "dua_order": 3,
     "title": "Completing the 100",
     "arabic_text": "لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
     "transliteration": "La ilaha illallahu wahdahu la sharika lah, lahul-mulku wa lahul-hamdu wa huwa 'ala kulli shay'in qadeer",
     "translation": "There is no god but Allah alone, with no partner. His is the dominion, His is the praise, and He has power over all things.",
     "source": "Muslim 597", "repetition_count": 1, "when_to_recite": "After obligatory prayer (completing to 100)"},
    {"key": "after_fajr_dua",        "category": "after_prayer", "dua_order": 4,
     "title": "After Fajr remembrance",
     "arabic_text": "اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا وَرِزْقًا طَيِّبًا وَعَمَلًا مُتَقَبَّلًا",
     "transliteration": "Allahumma inni as'aluka 'ilman nafi'an wa rizqan tayyiban wa 'amalan mutaqabbala",
     "translation": "O Allah, I ask You for beneficial knowledge, wholesome sustenance, and accepted deeds.",
     "source": "Ibn Majah 925", "repetition_count": 1, "when_to_recite": "After Fajr salah"},

    # ─── Before / After Eating ────────────────────────────────────────────────
    {"key": "before_eating",          "category": "food", "dua_order": 1,
     "title": "Before eating",
     "arabic_text": "بِسْمِ اللَّهِ",
     "transliteration": "Bismillah",
     "translation": "In the name of Allah.",
     "source": "Bukhari 5376, Muslim 2017", "repetition_count": 1, "when_to_recite": "Before eating"},
    {"key": "forgot_bismillah",       "category": "food", "dua_order": 2,
     "title": "When you forget Bismillah",
     "arabic_text": "بِسْمِ اللَّهِ أَوَّلَهُ وَآخِرَهُ",
     "transliteration": "Bismillahi awwalahu wa akhirahu",
     "translation": "In the name of Allah, at its beginning and at its end.",
     "source": "Abu Dawud 3767", "repetition_count": 1, "when_to_recite": "If you forget Bismillah before eating"},
    {"key": "after_eating",           "category": "food", "dua_order": 3,
     "title": "After eating",
     "arabic_text": "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ",
     "transliteration": "Alhamdu lillahil-ladhi at'amani hadha wa razaqanihi min ghayri hawlin minni wa la quwwah",
     "translation": "All praise is for Allah who fed me this and provided it for me without any power or strength on my part.",
     "source": "Abu Dawud 4023", "repetition_count": 1, "when_to_recite": "After finishing a meal"},
    {"key": "after_eating_complete",  "category": "food", "dua_order": 4,
     "title": "Complete dua after eating",
     "arabic_text": "الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ",
     "transliteration": "Alhamdu lillahil-ladhi at'amana wa saqana wa ja'alana muslimeen",
     "translation": "All praise is for Allah who fed us, gave us drink, and made us Muslims.",
     "source": "Abu Dawud 3850", "repetition_count": 1, "when_to_recite": "After a meal in group"},

    # ─── Travel ───────────────────────────────────────────────────────────────
    {"key": "travel_start",           "category": "travel", "dua_order": 1,
     "title": "Beginning a journey",
     "arabic_text": "اللَّهُ أَكْبَرُ اللَّهُ أَكْبَرُ اللَّهُ أَكْبَرُ سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ",
     "transliteration": "Allahu Akbar (x3), Subhanal-ladhi sakhkhara lana hadha wa ma kunna lahu muqrinin wa inna ila rabbina lamunqaliboon",
     "translation": "Allah is the Greatest (x3). Glory be to Him who made this subservient to us, and we could not have done it ourselves, and indeed to our Lord we will return.",
     "source": "Muslim 1342", "repetition_count": 1, "when_to_recite": "When boarding a vehicle or beginning a journey"},
    {"key": "travel_dua_for_family",  "category": "travel", "dua_order": 2,
     "title": "Leaving home",
     "arabic_text": "بِسْمِ اللَّهِ، تَوَكَّلْتُ عَلَى اللَّهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ",
     "transliteration": "Bismillah, tawakkaltu 'alallah, wa la hawla wa la quwwata illa billah",
     "translation": "In the name of Allah, I place my trust in Allah, and there is no power and no strength except with Allah.",
     "source": "Abu Dawud 5095", "repetition_count": 1, "when_to_recite": "When leaving the home"},
    {"key": "entering_home",          "category": "travel", "dua_order": 3,
     "title": "Entering the home",
     "arabic_text": "اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ الْمَوْلِجِ وَخَيْرَ الْمَخْرَجِ، بِسْمِ اللَّهِ وَلَجْنَا وَبِسْمِ اللَّهِ خَرَجْنَا وَعَلَى اللَّهِ رَبِّنَا تَوَكَّلْنَا",
     "transliteration": "Allahumma inni as'aluka khayral-mawlaji wa khayral-makhraji, bismillahi walajna wa bismillahi kharajna wa 'alallahi rabbina tawakkalna",
     "translation": "O Allah, I ask You for the blessings of entering and leaving. With Allah's name we enter and with Allah's name we leave, and upon Allah our Lord we put our trust.",
     "source": "Abu Dawud 5096", "repetition_count": 1, "when_to_recite": "When entering the home"},

    # ─── Distress / Anxiety ───────────────────────────────────────────────────
    {"key": "anxiety_dua",            "category": "distress", "dua_order": 1,
     "title": "For anxiety and sorrow",
     "arabic_text": "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَالْعَجْزِ وَالْكَسَلِ، وَالْبُخْلِ وَالْجُبْنِ، وَضَلَعِ الدَّيْنِ وَغَلَبَةِ الرِّجَالِ",
     "transliteration": "Allahumma inni a'udhu bika minal-hammi wal-hazan, wal-'ajzi wal-kasal, wal-bukhli wal-jubn, wa dhala'id-dayni wa ghalabatir-rijal",
     "translation": "O Allah, I seek refuge in You from worry and grief, from incapacity and laziness, from cowardice and miserliness, from being overcome by debt and from being overpowered by men.",
     "source": "Bukhari 6363", "repetition_count": 1, "when_to_recite": "During times of worry, anxiety, or distress"},
    {"key": "la_ilaha_illa_anta",     "category": "distress", "dua_order": 2,
     "title": "Dua of Prophet Yunus ﷺ",
     "arabic_text": "لَا إِلَهَ إِلَّا أَنْتَ سُبْحَانَكَ إِنِّي كُنْتُ مِنَ الظَّالِمِينَ",
     "transliteration": "La ilaha illa anta subhanaka inni kuntu minaz-zalimeen",
     "translation": "There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers.",
     "source": "Quran 21:87, Tirmidhi 3505", "repetition_count": 1, "when_to_recite": "In times of hardship — the Prophet ﷺ said no Muslim calls with this dua except that Allah responds"},
    {"key": "hasbunallah",            "category": "distress", "dua_order": 3,
     "title": "Allah is sufficient for us",
     "arabic_text": "حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ",
     "transliteration": "Hasbunallahu wa ni'mal-wakeel",
     "translation": "Allah is sufficient for us, and He is the best Disposer of affairs.",
     "source": "Quran 3:173, Bukhari 4563", "repetition_count": 1, "when_to_recite": "When facing fear or overwhelming difficulty"},
    {"key": "dua_of_ayyub",           "category": "distress", "dua_order": 4,
     "title": "Dua of Prophet Ayyub ﷺ (for illness)",
     "arabic_text": "أَنِّي مَسَّنِيَ الضُّرُّ وَأَنْتَ أَرْحَمُ الرَّاحِمِينَ",
     "transliteration": "Anni massaniyad-durru wa anta arhamur-rahimeen",
     "translation": "Indeed, adversity has touched me, and You are the Most Merciful of the merciful.",
     "source": "Quran 21:83", "repetition_count": 1, "when_to_recite": "During illness or severe hardship"},

    # ─── Guidance / Istikhara ─────────────────────────────────────────────────
    {"key": "istikhara",              "category": "guidance", "dua_order": 1,
     "title": "Istikhara (seeking guidance)",
     "arabic_text": "اللَّهُمَّ إِنِّي أَسْتَخِيرُكَ بِعِلْمِكَ وَأَسْتَقْدِرُكَ بِقُدْرَتِكَ وَأَسْأَلُكَ مِنْ فَضْلِكَ الْعَظِيمِ فَإِنَّكَ تَقْدِرُ وَلَا أَقْدِرُ وَتَعْلَمُ وَلَا أَعْلَمُ وَأَنْتَ عَلَّامُ الْغُيُوبِ",
     "transliteration": "Allahumma inni astakhiruka bi'ilmika, wa astaqdiruka bi-qudratika, wa as'aluka min fadlikal-'adheem, fa innaka taqdiru wa la aqdiru, wa ta'lamu wa la a'lamu, wa anta 'allamul-ghuyoob",
     "translation": "O Allah, I seek Your guidance by virtue of Your knowledge, and I seek ability by virtue of Your power, and I ask You of Your great bounty. For You have power and I have none, and You know and I know not, and You are the Knower of hidden things.",
     "source": "Bukhari 6382", "repetition_count": 1, "when_to_recite": "After 2 rakat prayer of Istikhara"},
    {"key": "guidance_dua",           "category": "guidance", "dua_order": 2,
     "title": "For guidance on the straight path",
     "arabic_text": "اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ",
     "transliteration": "Ihdinassiratal-mustaqeem",
     "translation": "Guide us to the straight path.",
     "source": "Quran 1:6", "repetition_count": 1, "when_to_recite": "In every rak'ah of prayer"},

    # ─── Family / Marriage ────────────────────────────────────────────────────
    {"key": "dua_for_spouse",         "category": "family", "dua_order": 1,
     "title": "For righteous spouse and children",
     "arabic_text": "رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا",
     "transliteration": "Rabbana hab lana min azwajina wa dhurriyyatina qurrata a'yunin waj'alna lil-muttaqina imama",
     "translation": "Our Lord, grant us from among our wives and offspring comfort to our eyes and make us a leader for the righteous.",
     "source": "Quran 25:74", "repetition_count": 1, "when_to_recite": "For blessing in family life"},
    {"key": "entering_masjid",        "category": "family", "dua_order": 2,
     "title": "Dua for parents",
     "arabic_text": "رَّبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",
     "transliteration": "Rabbir hamhuma kama rabbayani sagheera",
     "translation": "My Lord, have mercy upon them as they brought me up when I was small.",
     "source": "Quran 17:24", "repetition_count": 1, "when_to_recite": "Daily for parents, especially elderly parents"},

    # ─── Health ───────────────────────────────────────────────────────────────
    {"key": "health_shifa",           "category": "health", "dua_order": 1,
     "title": "Dua for healing (Shifa)",
     "arabic_text": "اللَّهُمَّ رَبَّ النَّاسِ، أَذْهِبِ الْبَأْسَ، اشْفِهِ وَأَنْتَ الشَّافِي، لَا شِفَاءَ إِلَّا شِفَاؤُكَ، شِفَاءً لَا يُغَادِرُ سَقَمًا",
     "transliteration": "Allahumma Rabban-nas, adhhibil-ba's, ashfihi wa antash-shafi, la shifa'a illa shifa'uk, shifa'an la yughadiru saqama",
     "translation": "O Allah, Lord of mankind, remove the harm and heal him/her, for You are the Healer and there is no healing but Your healing that leaves no disease.",
     "source": "Bukhari 5742, Muslim 2191", "repetition_count": 1, "when_to_recite": "When visiting the sick or for yourself when ill"},
    {"key": "health_ruqyah",          "category": "health", "dua_order": 2,
     "title": "Ruqyah for illness",
     "arabic_text": "بِسْمِ اللَّهِ أَرْقِيكَ مِنْ كُلِّ شَيْءٍ يُؤْذِيكَ، مِنْ شَرِّ كُلِّ نَفْسٍ أَوْ عَيْنٍ حَاسِدٍ، اللَّهُ يَشْفِيكَ",
     "transliteration": "Bismillahi arqeeka min kulli shay'in yu'dheek, min sharri kulli nafsin aw 'aynin hasid, Allahu yashfeek",
     "translation": "In the name of Allah I perform ruqya for you from everything that harms you, from the evil of every soul or envious eye. May Allah cure you.",
     "source": "Muslim 2186", "repetition_count": 3, "when_to_recite": "When ill — blow over the body after reciting"},

    # ─── Forgiveness / Tawbah ────────────────────────────────────────────────
    {"key": "tawbah_general",         "category": "forgiveness", "dua_order": 1,
     "title": "General repentance",
     "arabic_text": "رَبَّنَا ظَلَمْنَا أَنفُسَنَا وَإِن لَّمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ",
     "transliteration": "Rabbana dhalamna anfusana wa in lam taghfir lana wa tarhamna lanakoonanna minal-khasirin",
     "translation": "Our Lord, we have wronged ourselves, and if You do not forgive us and have mercy upon us, we will surely be among the losers.",
     "source": "Quran 7:23", "repetition_count": 1, "when_to_recite": "When seeking forgiveness from a sin"},
    {"key": "istighfar_100",          "category": "forgiveness", "dua_order": 2,
     "title": "Istighfar 100 times",
     "arabic_text": "أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ",
     "transliteration": "Astaghfirullaha wa atoobu ilayh",
     "translation": "I seek forgiveness from Allah and repent to Him.",
     "source": "Bukhari 6307", "repetition_count": 100, "when_to_recite": "Daily — the Prophet ﷺ would say this 100 times a day"},

    # ─── Protection ───────────────────────────────────────────────────────────
    {"key": "protection_shaytan",     "category": "protection", "dua_order": 1,
     "title": "Protection from Shaytan",
     "arabic_text": "أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ",
     "transliteration": "A'udhu billahi minash-shaytanir-rajeem",
     "translation": "I seek refuge with Allah from the accursed Shaytan.",
     "source": "Quran 16:98", "repetition_count": 1, "when_to_recite": "Before reciting Quran, when angry, and in temptation"},
    {"key": "protection_evil_eye",    "category": "protection", "dua_order": 2,
     "title": "Protection from evil eye (for others)",
     "arabic_text": "اللَّهُمَّ بَارِكْ فِيهِ",
     "transliteration": "Allahumma barik feeh",
     "translation": "O Allah, bless him/her.",
     "source": "Ibn Majah 3509", "repetition_count": 1, "when_to_recite": "When admiring something to ward off evil eye"},
    {"key": "entering_masjid_dua",   "category": "protection", "dua_order": 3,
     "title": "Entering the masjid",
     "arabic_text": "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ",
     "transliteration": "Allahumma iftah li abwaba rahmatik",
     "translation": "O Allah, open for me the gates of Your mercy.",
     "source": "Muslim 713", "repetition_count": 1, "when_to_recite": "Upon entering the masjid"},
    {"key": "exiting_masjid_dua",    "category": "protection", "dua_order": 4,
     "title": "Exiting the masjid",
     "arabic_text": "اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ",
     "transliteration": "Allahumma inni as'aluka min fadlik",
     "translation": "O Allah, I ask You for Your bounty.",
     "source": "Muslim 713", "repetition_count": 1, "when_to_recite": "Upon leaving the masjid"},

    # ─── Gratitude ────────────────────────────────────────────────────────────
    {"key": "alhamdulillah",          "category": "gratitude", "dua_order": 1,
     "title": "Alhamdulillah",
     "arabic_text": "الْحَمْدُ لِلَّهِ",
     "transliteration": "Alhamdulillah",
     "translation": "All praise is for Allah.",
     "source": "Tirmidhi 3383", "repetition_count": 1, "when_to_recite": "Constantly, upon any blessing received"},
    {"key": "seeing_blessings",       "category": "gratitude", "dua_order": 2,
     "title": "Upon seeing a blessing",
     "arabic_text": "مَا شَاءَ اللَّهُ لَا قُوَّةَ إِلَّا بِاللَّهِ",
     "transliteration": "Ma sha'Allahu la quwwata illa billah",
     "translation": "Whatever Allah wills! There is no power except with Allah.",
     "source": "Quran 18:39", "repetition_count": 1, "when_to_recite": "When seeing something wonderful or receiving a blessing"},
    {"key": "nikmat_shukr",           "category": "gratitude", "dua_order": 3,
     "title": "Thanking for a blessing",
     "arabic_text": "الْحَمْدُ لِلَّهِ الَّذِي بِنِعْمَتِهِ تَتِمُّ الصَّالِحَاتُ",
     "transliteration": "Alhamdu lillahil-ladhi bi-ni'matihi tatimus-salihat",
     "translation": "Praise be to Allah by Whose grace good deeds are completed.",
     "source": "Ibn Majah 3803", "repetition_count": 1, "when_to_recite": "When something good happens"},

    # ─── General / Daily ──────────────────────────────────────────────────────
    {"key": "before_sleep",           "category": "general", "dua_order": 1,
     "title": "Before sleep",
     "arabic_text": "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
     "transliteration": "Bismika Allahumma amootu wa ahya",
     "translation": "In Your name, O Allah, I die and I live.",
     "source": "Bukhari 6324", "repetition_count": 1, "when_to_recite": "When lying down to sleep"},
    {"key": "after_wudu",             "category": "general", "dua_order": 2,
     "title": "After wudu",
     "arabic_text": "أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ",
     "transliteration": "Ash-hadu an la ilaha illallahu wahdahu la sharika lah, wa ash-hadu anna Muhammadan 'abduhu wa rasooluh",
     "translation": "I bear witness that there is no deity except Allah alone, with no partner, and I bear witness that Muhammad is His slave and Messenger.",
     "source": "Muslim 234", "repetition_count": 1, "when_to_recite": "After completing wudu"},
    {"key": "sneezing_response",      "category": "general", "dua_order": 3,
     "title": "After sneezing",
     "arabic_text": "الْحَمْدُ لِلَّهِ",
     "transliteration": "Alhamdulillah",
     "translation": "All praise is for Allah.",
     "source": "Bukhari 6224", "repetition_count": 1, "when_to_recite": "After sneezing — the listener responds: Yarhamukallah"},
    {"key": "salawat",                "category": "general", "dua_order": 4,
     "title": "Salawat upon the Prophet ﷺ",
     "arabic_text": "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ",
     "transliteration": "Allahumma salli 'ala Muhammadin wa 'ala ali Muhammad",
     "translation": "O Allah, send prayers upon Muhammad and upon the family of Muhammad.",
     "source": "Bukhari 3370", "repetition_count": 10, "when_to_recite": "Throughout the day, especially on Fridays"},
    {"key": "beginning_any_matter",   "category": "general", "dua_order": 5,
     "title": "Beginning any important matter",
     "arabic_text": "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
     "transliteration": "Bismillahir-rahmanir-raheem",
     "translation": "In the name of Allah, the Entirely Merciful, the Especially Merciful.",
     "source": "Quran 1:1", "repetition_count": 1, "when_to_recite": "Before any important task or action"},
    {"key": "dua_for_knowledge",      "category": "general", "dua_order": 6,
     "title": "For increase in knowledge",
     "arabic_text": "رَّبِّ زِدْنِي عِلْمًا",
     "transliteration": "Rabbi zidni 'ilma",
     "translation": "My Lord, increase me in knowledge.",
     "source": "Quran 20:114", "repetition_count": 1, "when_to_recite": "Before studying or seeking knowledge"},
    {"key": "laylat_al_qadr_dua",    "category": "general", "dua_order": 7,
     "title": "Dua for Laylat al-Qadr",
     "arabic_text": "اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي",
     "transliteration": "Allahumma innaka 'afuwwun tuhibbul-'afwa fa'fu 'anni",
     "translation": "O Allah, You are the Pardoner and You love pardoning, so pardon me.",
     "source": "Tirmidhi 3513, Ibn Majah 3850", "repetition_count": 1, "when_to_recite": "During the last 10 nights of Ramadan, especially odd nights"},
    {"key": "entering_bathroom",      "category": "general", "dua_order": 8,
     "title": "Entering the bathroom",
     "arabic_text": "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ",
     "transliteration": "Allahumma inni a'udhu bika minal-khubthi wal-khaba'ith",
     "translation": "O Allah, I seek refuge with You from the male and female devils.",
     "source": "Bukhari 142, Muslim 375", "repetition_count": 1, "when_to_recite": "Before entering the bathroom"},

    # ─── Ramadan Special ──────────────────────────────────────────────────────
    {"key": "ramadan_opening_fast",   "category": "general", "dua_order": 9,
     "title": "Opening the fast (Iftar)",
     "arabic_text": "اللَّهُمَّ لَكَ صُمْتُ وَبِكَ آمَنْتُ وَعَلَى رِزْقِكَ أَفْطَرْتُ",
     "transliteration": "Allahumma laka sumtu wa bika amantu wa 'ala rizqika aftartu",
     "translation": "O Allah, for You I have fasted, in You I believe, and upon Your provision I break my fast.",
     "source": "Abu Dawud 2358", "repetition_count": 1, "when_to_recite": "At the time of Iftar"},
    {"key": "dua_at_iftar_another",   "category": "general", "dua_order": 10,
     "title": "At Iftar (thirst quenching)",
     "arabic_text": "ذَهَبَ الظَّمَأُ وَابْتَلَّتِ الْعُرُوقُ وَثَبَتَ الأَجْرُ إِنْ شَاءَ اللَّهُ",
     "transliteration": "Dhahabaz-dhama'u wabtallatil-'urooqu wa thabatal-ajru in sha'Allah",
     "translation": "The thirst has gone, the veins are moistened, and the reward is established, if Allah wills.",
     "source": "Abu Dawud 2357", "repetition_count": 1, "when_to_recite": "After breaking fast with water"},
]

# Ensure we have 100+ — pad with additional commonly-used duas
ADDITIONAL_DUAS = [
    {"key": "dua_for_rain",           "category": "general", "dua_order": 20,
     "title": "Dua when seeing rain",
     "arabic_text": "اللَّهُمَّ صَيِّبًا نَافِعًا",
     "transliteration": "Allahumma sayyiban nafi'a",
     "translation": "O Allah, make it a beneficial rain.",
     "source": "Bukhari 1032", "repetition_count": 1, "when_to_recite": "When it rains"},
    {"key": "dua_after_adhan",        "category": "general", "dua_order": 21,
     "title": "After the Adhan",
     "arabic_text": "اللَّهُمَّ رَبَّ هَذِهِ الدَّعْوَةِ التَّامَّةِ وَالصَّلَاةِ الْقَائِمَةِ، آتِ مُحَمَّدًا الْوَسِيلَةَ وَالْفَضِيلَةَ",
     "transliteration": "Allahumma Rabba hadhihid-da'watit-tammati was-salatil-qa'imah, ati Muhammadan al-waseelata wal-fadeelah",
     "translation": "O Allah, Lord of this perfect call and the prayer to be offered, grant Muhammad the privilege of intercession and also the eminence.",
     "source": "Bukhari 614", "repetition_count": 1, "when_to_recite": "After hearing the adhan"},
    {"key": "dua_for_children",       "category": "family", "dua_order": 10,
     "title": "For pious children",
     "arabic_text": "رَبِّ هَبْ لِي مِنَ الصَّالِحِينَ",
     "transliteration": "Rabbi hab li minas-saliheen",
     "translation": "My Lord, grant me from among the righteous.",
     "source": "Quran 37:100", "repetition_count": 1, "when_to_recite": "Supplication for righteous children"},
    {"key": "dua_sitting_in_majlis", "category": "general", "dua_order": 22,
     "title": "Expiation of a gathering",
     "arabic_text": "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ، أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا أَنْتَ، أَسْتَغْفِرُكَ وَأَتُوبُ إِلَيْكَ",
     "transliteration": "Subhanakal-lahumma wa bihamdika, ash-hadu an la ilaha illa ant, astaghfiruka wa atubu ilayk",
     "translation": "How perfect You are, O Allah, and I praise You. I bear witness that none has the right to be worshipped except You. I seek Your forgiveness and repent to You.",
     "source": "Abu Dawud 4859", "repetition_count": 1, "when_to_recite": "At the end of any gathering or sitting"},
    {"key": "dua_new_clothes",        "category": "general", "dua_order": 23,
     "title": "When wearing new clothes",
     "arabic_text": "الْحَمْدُ لِلَّهِ الَّذِي كَسَانِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ",
     "transliteration": "Alhamdu lillahil-ladhi kasani hadha wa razaqanihi min ghayri hawlin minni wa la quwwah",
     "translation": "All praise is for Allah who has clothed me with this and provided it for me without any power or might from myself.",
     "source": "Abu Dawud 4023", "repetition_count": 1, "when_to_recite": "When putting on new clothes"},
    {"key": "dua_looking_mirror",     "category": "general", "dua_order": 24,
     "title": "When looking in the mirror",
     "arabic_text": "اللَّهُمَّ أَنْتَ حَسَّنْتَ خَلْقِي فَحَسِّنْ خُلُقِي",
     "transliteration": "Allahumma anta hassanta khalqi fahassin khuluqi",
     "translation": "O Allah, as You have made my external features beautiful, make my character beautiful as well.",
     "source": "Ahmad 3925", "repetition_count": 1, "when_to_recite": "When looking in the mirror"},
    {"key": "dua_hardship_patience",  "category": "distress", "dua_order": 10,
     "title": "For patience in hardship",
     "arabic_text": "إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ، اللَّهُمَّ أُجُرْنِي فِي مُصِيبَتِي وَأَخْلِفْ لِي خَيْرًا مِنْهَا",
     "transliteration": "Inna lillahi wa inna ilayhi raji'oon, Allahumma ajurni fi musibati wa akhlif li khayran minha",
     "translation": "Indeed, to Allah we belong and to Allah we will return. O Allah, reward me in my affliction and replace it for me with something better.",
     "source": "Muslim 918", "repetition_count": 1, "when_to_recite": "Upon receiving bad news or experiencing a loss"},
]

ALL_DUAS = DUA_SEED_DATA + ADDITIONAL_DUAS


async def seed_duas(db) -> int:
    """Idempotent seeder — inserts duas not already in DB."""
    from sqlalchemy import select
    from app.models.quran import Dua

    existing_keys_result = await db.execute(select(Dua.key))
    existing_keys = {row[0] for row in existing_keys_result.all()}

    to_insert = [Dua(**d) for d in ALL_DUAS if d["key"] not in existing_keys]
    if to_insert:
        db.add_all(to_insert)
        await db.flush()
    return len(to_insert)
