"""
Islamic Habit Library — 120+ pre-built habits
=============================================
Each habit carries:
  - Islamic source (Quran / Hadith reference)
  - Why it matters (brief spiritual explanation)
  - Minimum version (Tiny Habits starting point)
  - Estimated time
  - Difficulty rating
  - Anchor prayer (which salah to stack after)
  - Category and habit type
"""

HABIT_LIBRARY = [
    # ─── Salah (8) ─────────────────────────────────────────────────────────
    {"key": "fajr_ontime", "name": "Pray Fajr on time", "category": "ibadah", "habit_type": "binary", "difficulty": "hard",
     "icon": "🌅", "target_count": 1, "unit": "prayer",
     "islamic_source": "Bukhari 543 — 'The best deed is prayer at its proper time'",
     "minimum_version": "Set two alarms: one at Fajr start, one 10 min before sunrise",
     "estimated_minutes": 10, "anchor_prayer": None,
     "description": "Pray Fajr before sunrise every day"},
    {"key": "all_five_prayers", "name": "Pray all 5 prayers on time", "category": "ibadah", "habit_type": "quantity", "difficulty": "medium",
     "icon": "🕌", "target_count": 5, "unit": "prayers",
     "islamic_source": "Quran 2:238 — 'Guard strictly the prayers'",
     "minimum_version": "Start by logging each prayer — awareness before perfection",
     "estimated_minutes": 30, "anchor_prayer": None,
     "description": "Complete all 5 obligatory prayers"},
    {"key": "sunnah_prayers", "name": "Pray 12 daily Sunnah rakat", "category": "ibadah", "habit_type": "quantity", "difficulty": "medium",
     "icon": "⭐", "target_count": 12, "unit": "rakat",
     "islamic_source": "Tirmidhi 414 — Whoever prays 12 rakat daily, a house is built for him in Paradise",
     "minimum_version": "Start with 2 rakat after Fajr — just 3 minutes",
     "estimated_minutes": 20, "anchor_prayer": "fajr",
     "description": "2 Fajr + 4 Dhuhr + 2 after Dhuhr + 2 Asr + 2 Maghrib + 2 Isha"},
    {"key": "tahajjud", "name": "Pray Tahajjud", "category": "ibadah", "habit_type": "binary", "difficulty": "epic",
     "icon": "🌙", "target_count": 1, "unit": "session",
     "islamic_source": "Quran 17:79 — 'And in some parts of the night, pray Tahajjud as an additional prayer'",
     "minimum_version": "Sleep after Isha, set alarm 30 min before Fajr. Pray just 2 rakat",
     "estimated_minutes": 20, "anchor_prayer": "fajr",
     "description": "Night prayer before Fajr — minimum 2 rakat"},
    {"key": "jumuah_early", "name": "Attend Jumuah early", "category": "ibadah", "habit_type": "binary", "difficulty": "easy",
     "icon": "🕌", "target_count": 1, "unit": "Friday",
     "islamic_source": "Muslim 850 — 'Whoever goes early to Jumuah is like one who sacrifices a camel'",
     "minimum_version": "Arrive 15 minutes before khutbah starts",
     "estimated_minutes": 60, "anchor_prayer": "dhuhr",
     "description": "Attend Friday prayer and arrive early"},
    {"key": "duha_prayer", "name": "Pray Duha (Chast prayer)", "category": "ibadah", "habit_type": "binary", "difficulty": "easy",
     "icon": "🌤", "target_count": 1, "unit": "session",
     "islamic_source": "Muslim 720 — 'The Prophet never abandoned Duha — 2, 4, 6, or 8 rakat'",
     "minimum_version": "Pray 2 rakat between sunrise + 20 min and before noon",
     "estimated_minutes": 8, "anchor_prayer": "fajr",
     "description": "2–8 rakat between mid-morning and before Dhuhr"},
    {"key": "witr_prayer", "name": "Pray Witr before sleep", "category": "ibadah", "habit_type": "binary", "difficulty": "easy",
     "icon": "🌑", "target_count": 1, "unit": "prayer",
     "islamic_source": "Abu Dawud 1416 — 'Make Witr your last prayer of the night'",
     "minimum_version": "Pray 1 rakat of Witr before sleeping — takes under 2 minutes",
     "estimated_minutes": 5, "anchor_prayer": "isha",
     "description": "Witr prayer after Isha before sleep"},
    {"key": "congregation_prayer", "name": "Pray in congregation", "category": "ibadah", "habit_type": "quantity", "difficulty": "medium",
     "icon": "👥", "target_count": 1, "unit": "prayers",
     "islamic_source": "Bukhari 645 — Congregation prayer is 27 times better than prayer alone",
     "minimum_version": "Start with one congregational prayer per day",
     "estimated_minutes": 15, "anchor_prayer": "maghrib",
     "description": "Pray at least one fard prayer in congregation"},

    # ─── Quran (8) ─────────────────────────────────────────────────────────
    {"key": "quran_daily_page", "name": "Read 1 page of Quran daily", "category": "quran", "habit_type": "quantity", "difficulty": "easy",
     "icon": "📖", "target_count": 1, "unit": "pages",
     "islamic_source": "Tirmidhi 2910 — 'Whoever reads one letter gets 10 rewards'",
     "minimum_version": "Read 3 ayat from where you left off — bookmark your place",
     "estimated_minutes": 5, "anchor_prayer": "fajr",
     "description": "Consistent daily Quran reading"},
    {"key": "quran_juz_weekly", "name": "Complete 1 Juz per week", "category": "quran", "habit_type": "quantity", "difficulty": "medium",
     "icon": "📖", "target_count": 4, "unit": "pages",
     "islamic_source": "Ibn Abbas (RA) recommended completing one khatam per month",
     "minimum_version": "Read 4 pages daily — one after each of the first 4 prayers",
     "estimated_minutes": 20, "anchor_prayer": None,
     "description": "Read 4 pages/day to complete 1 Juz per week"},
    {"key": "quran_memorise", "name": "Memorise new Quran daily", "category": "quran", "habit_type": "quantity", "difficulty": "hard",
     "icon": "🧠", "target_count": 3, "unit": "ayat",
     "islamic_source": "Bukhari 5027 — 'The best of you are those who learn and teach the Quran'",
     "minimum_version": "Memorise just 1 ayah per day with its meaning",
     "estimated_minutes": 15, "anchor_prayer": "fajr",
     "description": "New memorisation session every morning"},
    {"key": "quran_review", "name": "Review Hifz daily", "category": "quran", "habit_type": "quantity", "difficulty": "medium",
     "icon": "🔄", "target_count": 1, "unit": "pages",
     "islamic_source": "Bukhari 5031 — 'Keep refreshing knowledge of the Quran, for it is more fleeting than camels'",
     "minimum_version": "Recite 1 page of memorised Quran — even while commuting",
     "estimated_minutes": 10, "anchor_prayer": "fajr",
     "description": "Daily review of previously memorised Quran"},
    {"key": "quran_tafsir", "name": "Read Tafsir weekly", "category": "quran", "habit_type": "binary", "difficulty": "easy",
     "icon": "📚", "target_count": 1, "unit": "session",
     "islamic_source": "Quran 38:29 — '...that they may ponder its verses'",
     "minimum_version": "Read the tafsir of 1 ayah you recently recited",
     "estimated_minutes": 20, "anchor_prayer": None,
     "description": "Weekly deep dive into Quran tafsir"},
    {"key": "recite_fajr_surahs", "name": "Recite Surah Al-Mulk nightly", "category": "quran", "habit_type": "binary", "difficulty": "easy",
     "icon": "🌙", "target_count": 1, "unit": "recitation",
     "islamic_source": "Tirmidhi 2891 — Al-Mulk intercedes for its reciter in the grave",
     "minimum_version": "Read from mushaf until you memorise — 10 minutes",
     "estimated_minutes": 10, "anchor_prayer": "isha",
     "description": "Nightly recitation of Surah Al-Mulk before sleep"},
    {"key": "quran_listening", "name": "Listen to Quran 20 min/day", "category": "quran", "habit_type": "duration", "difficulty": "easy",
     "icon": "🎧", "target_count": 20, "unit": "minutes",
     "islamic_source": "Tirmidhi 2910 — Every letter carries 10 rewards, whether read or heard attentively",
     "minimum_version": "Play Quran during morning routine — no separate time needed",
     "estimated_minutes": 20, "anchor_prayer": None,
     "description": "Attentive listening to Quran recitation daily"},
    {"key": "quran_arabic_word", "name": "Learn 3 Quran vocabulary words", "category": "quran", "habit_type": "quantity", "difficulty": "easy",
     "icon": "🔤", "target_count": 3, "unit": "words",
     "islamic_source": "Quran 20:114 — 'My Lord, increase me in knowledge'",
     "minimum_version": "Learn just 1 word from today's recitation",
     "estimated_minutes": 5, "anchor_prayer": "fajr",
     "description": "Daily Quranic Arabic vocabulary building"},

    # ─── Dhikr & Adhkar (8) ────────────────────────────────────────────────
    {"key": "morning_adhkar", "name": "Morning adhkar (full)", "category": "dhikr", "habit_type": "checklist", "difficulty": "medium",
     "icon": "📿", "target_count": 1, "unit": "session",
     "islamic_source": "Abu Dawud 5082 — Morning/evening adhkar from the Sunnah",
     "minimum_version": "Start with Ayat al-Kursi + 3 Quls × 3",
     "estimated_minutes": 10, "anchor_prayer": "fajr",
     "description": "Complete morning remembrance after Fajr",
     "checklist_items": [
         {"label": "Ayat al-Kursi", "arabic_text": "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ ٱلْحَىُّ ٱلْقَيُّومُ", "repetition_count": 1},
         {"label": "Surah Al-Ikhlas", "arabic_text": "قُلْ هُوَ اللَّهُ أَحَدٌ", "repetition_count": 3},
         {"label": "Surah Al-Falaq", "arabic_text": "قُلْ أَعُوذُ بِرَبِّ ٱلْفَلَقِ", "repetition_count": 3},
         {"label": "Surah An-Nas", "arabic_text": "قُلْ أَعُوذُ بِرَبِّ ٱلنَّاسِ", "repetition_count": 3},
         {"label": "Sayyid al-Istighfar", "repetition_count": 1}
     ]},
    {"key": "evening_adhkar", "name": "Evening adhkar (full)", "category": "dhikr", "habit_type": "checklist", "difficulty": "medium",
     "icon": "🌆", "target_count": 1, "unit": "session",
     "islamic_source": "Abu Dawud 5082 — Before Maghrib adhkar",
     "minimum_version": "Start with just SubhanAllahi wa bihamdih × 100",
     "estimated_minutes": 10, "anchor_prayer": "asr",
     "description": "Complete evening remembrance before Maghrib",
     "checklist_items": [
         {"label": "Ayat al-Kursi", "arabic_text": "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ ٱلْحَىُّ ٱلْقَيُّومُ", "repetition_count": 1},
         {"label": "Surah Al-Ikhlas", "arabic_text": "قُلْ هُوَ اللَّهُ أَحَدٌ", "repetition_count": 3},
         {"label": "Surah Al-Falaq", "arabic_text": "قُلْ أَعُوذُ بِرَبِّ ٱلْفَلَقِ", "repetition_count": 3},
         {"label": "Surah An-Nas", "arabic_text": "قُلْ أَعُوذُ بِرَبِّ ٱلنَّاسِ", "repetition_count": 3},
         {"label": "Sayyid al-Istighfar", "repetition_count": 1}
     ]},
    {"key": "subhanallah_100", "name": "SubhanAllahi wa bihamdih ×100", "category": "dhikr", "habit_type": "quantity", "difficulty": "easy",
     "icon": "📿", "target_count": 100, "unit": "times",
     "islamic_source": "Bukhari 6405 — Forgives sins like foam of the sea",
     "minimum_version": "Say it 33 times morning and evening — 2 min each",
     "estimated_minutes": 5, "anchor_prayer": "fajr",
     "description": "Daily SubhanAllah wa bihamdih 100 times"},
    {"key": "istighfar_100", "name": "Astaghfirullah ×100 daily", "category": "dhikr", "habit_type": "quantity", "difficulty": "easy",
     "icon": "🤲", "target_count": 100, "unit": "times",
     "islamic_source": "Bukhari 6307 — The Prophet ﷺ sought forgiveness 100+ times daily",
     "minimum_version": "Say it 10 times after each prayer = 50 times",
     "estimated_minutes": 3, "anchor_prayer": "isha",
     "description": "Daily istighfar 100 times"},
    {"key": "salawat_100", "name": "Salawat upon the Prophet ﷺ ×100", "category": "dhikr", "habit_type": "quantity", "difficulty": "easy",
     "icon": "💚", "target_count": 100, "unit": "times",
     "islamic_source": "Muslim 408 — Whoever sends salawat 10 times, Allah sends mercy on him 100 times",
     "minimum_version": "Send salawat 10 times after each prayer = 50 times",
     "estimated_minutes": 5, "anchor_prayer": None,
     "description": "Send salawat upon the Prophet ﷺ 100 times daily"},
    {"key": "dhikr_after_prayer", "name": "Post-salah dhikr (33-33-33)", "category": "dhikr", "habit_type": "checklist", "difficulty": "easy",
     "icon": "📿", "target_count": 1, "unit": "session",
     "islamic_source": "Muslim 597 — SubhanAllah 33, Alhamdulillah 33, Allahu Akbar 33",
     "minimum_version": "One prayer at a time — start with after Fajr",
     "estimated_minutes": 3, "anchor_prayer": "fajr",
     "description": "Complete tasbih after every fard salah",
     "checklist_items": [
         {"label": "SubhanAllah", "arabic_text": "سُبْحَانَ اللَّهِ", "repetition_count": 33},
         {"label": "Alhamdulillah", "arabic_text": "الْحَمْدُ لِلَّهِ", "repetition_count": 33},
         {"label": "Allahu Akbar", "arabic_text": "اللَّهُ أَكْبَرُ", "repetition_count": 33},
         {"label": "La ilaha illAllah...", "arabic_text": "لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ", "repetition_count": 1}
     ]},
    {"key": "la_ilaha_dhikr", "name": "Tahlil (La ilaha illAllah) ×1000", "category": "dhikr", "habit_type": "quantity", "difficulty": "hard",
     "icon": "☝️", "target_count": 1000, "unit": "times",
     "islamic_source": "Ibn Majah 3794 — Renews iman and is the best dhikr",
     "minimum_version": "Start with 100 times — takes under 5 minutes",
     "estimated_minutes": 30, "anchor_prayer": None,
     "description": "Dedicated tahlil session — the word of pure monotheism"},
    {"key": "quran_before_sleep", "name": "Ayat al-Kursi + 3 Quls before sleep", "category": "dhikr", "habit_type": "checklist", "difficulty": "easy",
     "icon": "😴", "target_count": 1, "unit": "session",
     "islamic_source": "Bukhari 5017 — Whoever reads Ayat al-Kursi before sleep, an angel protects him till morning",
     "minimum_version": "Just Ayat al-Kursi — 30 seconds",
     "estimated_minutes": 3, "anchor_prayer": "isha",
     "description": "Bedtime protection supplications",
     "checklist_items": [
         {"label": "Ayat al-Kursi", "arabic_text": "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ ٱلْحَىُّ ٱلْقَيُّومُ", "repetition_count": 1},
         {"label": "Surah Al-Ikhlas", "arabic_text": "قُلْ هُوَ اللَّهُ أَحَدٌ", "repetition_count": 3},
         {"label": "Surah Al-Falaq", "arabic_text": "قُلْ أَعُوذُ بِرَبِّ ٱلْفَلَقِ", "repetition_count": 3},
         {"label": "Surah An-Nas", "arabic_text": "قُلْ أَعُوذُ بِرَبِّ ٱلنَّاسِ", "repetition_count": 3}
     ]},

    # ─── Fasting (5) ───────────────────────────────────────────────────────
    {"key": "monday_thursday_fast", "name": "Fast Monday and Thursday", "category": "fasting", "habit_type": "quantity", "difficulty": "medium",
     "icon": "🌙", "target_count": 2, "unit": "days",
     "islamic_source": "Tirmidhi 747 — The Prophet ﷺ loved to fast Mon/Thu because deeds are presented to Allah",
     "minimum_version": "Start with just Thursday — skip breakfast intentionally",
     "estimated_minutes": 0, "anchor_prayer": None,
     "description": "Sunnah fasting on Mondays and Thursdays"},
    {"key": "white_days_fast", "name": "Fast the 3 White Days (13-14-15)", "category": "fasting", "habit_type": "quantity", "difficulty": "medium",
     "icon": "🌕", "target_count": 3, "unit": "days",
     "islamic_source": "Nasai 2432 — It is as if you fasted the entire month",
     "minimum_version": "Fast just the 14th of the Hijri month — the middle white day",
     "estimated_minutes": 0, "anchor_prayer": None,
     "description": "Three white days of each Hijri month"},
    {"key": "shawwal_6_fasts", "name": "6 fasts of Shawwal", "category": "fasting", "habit_type": "quantity", "difficulty": "medium",
     "icon": "✨", "target_count": 6, "unit": "days",
     "islamic_source": "Muslim 1164 — Ramadan + 6 Shawwal = fasting the whole year",
     "minimum_version": "Fast 2 days each week of Shawwal",
     "estimated_minutes": 0, "anchor_prayer": None,
     "description": "Complete 6 fasts in the month of Shawwal"},
    {"key": "arafah_fast", "name": "Fast the Day of Arafah", "category": "fasting", "habit_type": "binary", "difficulty": "easy",
     "icon": "🕋", "target_count": 1, "unit": "day",
     "islamic_source": "Muslim 1162 — Expiates sins of two years",
     "minimum_version": "Mark it in your calendar — it's one day in the year",
     "estimated_minutes": 0, "anchor_prayer": None,
     "description": "Fast on 9 Dhul Hijjah — the greatest voluntary fast"},
    {"key": "ashura_fast", "name": "Fast Ashura (9th & 10th Muharram)", "category": "fasting", "habit_type": "quantity", "difficulty": "easy",
     "icon": "🌟", "target_count": 2, "unit": "days",
     "islamic_source": "Muslim 1162 — Expiates sins of the previous year",
     "minimum_version": "Fast just the 10th — add the 9th to oppose the Jews",
     "estimated_minutes": 0, "anchor_prayer": None,
     "description": "Fast the 9th and 10th of Muharram"},

    # ─── Sadaqah & Character (7) ────────────────────────────────────────────
    {"key": "daily_sadaqah", "name": "Give sadaqah daily", "category": "sadaqah", "habit_type": "binary", "difficulty": "easy",
     "icon": "💚", "target_count": 1, "unit": "act",
     "islamic_source": "Bukhari 1421 — Every day two angels descend; one says 'Replace what you spend'",
     "minimum_version": "Smile at someone — the Prophet ﷺ called it sadaqah",
     "estimated_minutes": 2, "anchor_prayer": "fajr",
     "description": "Any act of sadaqah daily — money, time, or kindness"},
    {"key": "friday_sadaqah", "name": "Give sadaqah on Jumu'ah", "category": "sadaqah", "habit_type": "binary", "difficulty": "easy",
     "icon": "🕌", "target_count": 1, "unit": "Friday",
     "islamic_source": "Bukhari 935 — Friday is the best day of the week for worship",
     "minimum_version": "Set aside even 1 coin every Friday morning",
     "estimated_minutes": 2, "anchor_prayer": "dhuhr",
     "description": "Weekly sadaqah on the blessed day of Jumu'ah"},
    {"key": "good_manners", "name": "Practice one act of ihsan daily", "category": "sadaqah", "habit_type": "binary", "difficulty": "easy",
     "icon": "😊", "target_count": 1, "unit": "act",
     "islamic_source": "Tirmidhi 2003 — 'The heaviest on the Scale: good character'",
     "minimum_version": "Morning intention: 'Today I will show ihsan to someone'",
     "estimated_minutes": 5, "anchor_prayer": "fajr",
     "description": "Intentional excellence in character every day"},
    {"key": "call_parents", "name": "Call parents daily", "category": "family", "habit_type": "binary", "difficulty": "easy",
     "icon": "📱", "target_count": 1, "unit": "call",
     "islamic_source": "Quran 17:23 — 'Say not to them a word of contempt'",
     "minimum_version": "Send a voice note if a call isn't possible",
     "estimated_minutes": 10, "anchor_prayer": "maghrib",
     "description": "Daily connection with parents"},
    {"key": "avoid_backbiting", "name": "Avoid backbiting (no ghibah)", "category": "avoid", "habit_type": "avoid", "difficulty": "hard",
     "icon": "🤐", "target_count": 0, "unit": "incidents",
     "islamic_source": "Quran 49:12 — 'Would any of you like to eat the flesh of his dead brother?'",
     "minimum_version": "Change the subject when backbiting starts",
     "estimated_minutes": 0, "anchor_prayer": None,
     "description": "Complete day without backbiting anyone"},
    {"key": "avoid_wasting_time", "name": "No mindless scrolling", "category": "avoid", "habit_type": "avoid", "difficulty": "epic",
     "icon": "📵", "target_count": 0, "unit": "incidents",
     "islamic_source": "Tirmidhi 2417 — 'Two blessings most people waste: health and free time'",
     "minimum_version": "Set one 30-min window for social media — remove apps from home screen",
     "estimated_minutes": 0, "anchor_prayer": None,
     "description": "Replace mindless scrolling with intentional activity"},
    {"key": "speak_good", "name": "Speak good or remain silent", "category": "sadaqah", "habit_type": "binary", "difficulty": "medium",
     "icon": "💬", "target_count": 1, "unit": "day",
     "islamic_source": "Bukhari 6018 — 'Whoever believes in Allah and the Last Day should speak good or remain silent'",
     "minimum_version": "Before each conversation: pause and ask 'Is this worth saying?'",
     "estimated_minutes": 0, "anchor_prayer": None,
     "description": "Intentional, truthful, and beneficial speech all day"},

    # ─── Knowledge (5) ─────────────────────────────────────────────────────
    {"key": "islamic_reading", "name": "Read Islamic book 20 min/day", "category": "learning", "habit_type": "duration", "difficulty": "easy",
     "icon": "📚", "target_count": 20, "unit": "minutes",
     "islamic_source": "Muslim 2699 — Seeking knowledge is a path to Paradise",
     "minimum_version": "Read 1 page of a scholar's biography at bedtime",
     "estimated_minutes": 20, "anchor_prayer": "isha",
     "description": "Daily Islamic reading from authenticated scholars"},
    {"key": "seerah_study", "name": "Study the Seerah weekly", "category": "learning", "habit_type": "binary", "difficulty": "easy",
     "icon": "🌟", "target_count": 1, "unit": "session",
     "islamic_source": "Quran 33:21 — 'In the Messenger of Allah you have an excellent example'",
     "minimum_version": "Listen to 1 Seerah podcast episode per week",
     "estimated_minutes": 30, "anchor_prayer": None,
     "description": "Weekly study of the Prophet's ﷺ biography"},
    {"key": "arabic_lesson", "name": "Arabic lesson daily", "category": "learning", "habit_type": "duration", "difficulty": "medium",
     "icon": "🔤", "target_count": 15, "unit": "minutes",
     "islamic_source": "Quran 12:2 — 'We have revealed it as an Arabic Quran'",
     "minimum_version": "Learn 1 new Arabic root word per day",
     "estimated_minutes": 15, "anchor_prayer": "fajr",
     "description": "Daily Arabic study toward Quranic comprehension"},
    {"key": "hadith_study", "name": "Study 1 hadith daily", "category": "learning", "habit_type": "binary", "difficulty": "easy",
     "icon": "📖", "target_count": 1, "unit": "hadith",
     "islamic_source": "Muslim 2699 — 'Whoever treads a path of knowledge, Allah eases his path to Paradise'",
     "minimum_version": "Read the Hadith of the Day in the app",
     "estimated_minutes": 5, "anchor_prayer": "fajr",
     "description": "Daily hadith with its explanation"},
    {"key": "dua_memorisation", "name": "Memorise 1 new dua weekly", "category": "learning", "habit_type": "binary", "difficulty": "easy",
     "icon": "🤲", "target_count": 1, "unit": "dua",
     "islamic_source": "Tirmidhi 3549 — 'The most beloved speech to Allah is that you invoke Him'",
     "minimum_version": "Learn 1 short dua (under 10 words) this week",
     "estimated_minutes": 10, "anchor_prayer": None,
     "description": "Weekly dua memorisation from authentic sources"},

    # ─── Physical Health (6) ────────────────────────────────────────────────
    {"key": "exercise_30min", "name": "Exercise 30 minutes daily", "category": "health", "habit_type": "duration", "difficulty": "medium",
     "icon": "🏃", "target_count": 30, "unit": "minutes",
     "islamic_source": "Bukhari 6094 — 'A strong believer is better and more beloved to Allah than a weak believer'",
     "minimum_version": "Walk for 10 minutes after Asr — fresh air is a blessing",
     "estimated_minutes": 30, "anchor_prayer": "asr",
     "description": "Daily movement for the amanah of the body"},
    {"key": "drink_8_glasses", "name": "Drink 8 glasses of water", "category": "health", "habit_type": "quantity", "difficulty": "easy",
     "icon": "💧", "target_count": 8, "unit": "glasses",
     "islamic_source": "Sunnah of the Prophet ﷺ — drink water while seated, in 3 sips, with Bismillah",
     "minimum_version": "Place a large water bottle beside your prayer mat",
     "estimated_minutes": 0, "anchor_prayer": None,
     "description": "Daily hydration following Sunnah drinking manners"},
    {"key": "sleep_before_midnight", "name": "Sleep before midnight", "category": "health", "habit_type": "binary", "difficulty": "medium",
     "icon": "😴", "target_count": 1, "unit": "night",
     "islamic_source": "Bukhari 6311 — The Prophet ﷺ disliked sleeping before Isha and talking after it",
     "minimum_version": "Set phone screen-off at 11pm, lie down at 11:30pm",
     "estimated_minutes": 0, "anchor_prayer": "isha",
     "description": "Early sleep for Fajr success and healthy cortisol"},
    {"key": "sunnah_foods", "name": "Eat 3 dates in the morning", "category": "health", "habit_type": "quantity", "difficulty": "easy",
     "icon": "🌴", "target_count": 3, "unit": "dates",
     "islamic_source": "Muslim 2047 — Whoever eats 7 ajwa dates in the morning is protected that day",
     "minimum_version": "Keep a small box of dates beside your Fajr prayer mat",
     "estimated_minutes": 1, "anchor_prayer": "fajr",
     "description": "Sunnah morning nourishment with dates"},
    {"key": "intermittent_fast", "name": "Eat within 8-hour window", "category": "health", "habit_type": "binary", "difficulty": "medium",
     "icon": "⏱", "target_count": 1, "unit": "day",
     "islamic_source": "Tirmidhi 2380 — 'No human fills a vessel worse than the stomach'",
     "minimum_version": "Skip late-night snacks after Isha",
     "estimated_minutes": 0, "anchor_prayer": None,
     "description": "Time-restricted eating aligned with Islamic moderation"},
    {"key": "no_phone_fajr", "name": "No phone 30 min after Fajr", "category": "avoid", "habit_type": "avoid", "difficulty": "hard",
     "icon": "📵", "target_count": 0, "unit": "phone checks",
     "islamic_source": "Tirmidhi 3598 — Morning dhikr and dua are the most blessed moments of the day",
     "minimum_version": "Charge phone in another room before sleeping",
     "estimated_minutes": 0, "anchor_prayer": "fajr",
     "description": "Protect the blessed morning window for worship"},

    # ─── Sunnah (additional, 10) ────────────────────────────────────────────
    {"key": "miswak", "name": "Use Miswak / brush teeth before prayer", "category": "sunnah", "habit_type": "binary", "difficulty": "easy",
     "icon": "🦷", "target_count": 1, "unit": "time",
     "islamic_source": "Bukhari 887 — 'Were it not for hardship, I would have ordered miswak before every prayer'",
     "minimum_version": "Use miswak before Fajr — just 30 seconds",
     "estimated_minutes": 1, "anchor_prayer": "fajr",
     "description": "Oral cleanliness sunnah before prayer"},
    {"key": "bismillah_everything", "name": "Say Bismillah before every action", "category": "sunnah", "habit_type": "binary", "difficulty": "easy",
     "icon": "✨", "target_count": 1, "unit": "day",
     "islamic_source": "Bukhari 5376 — Begin every permissible action in Allah's name",
     "minimum_version": "Set a phone reminder: 'Did you say Bismillah?' at 3 key times",
     "estimated_minutes": 0, "anchor_prayer": None,
     "description": "Intentional Bismillah before every action"},
    {"key": "right_first", "name": "Right side first (Sunnah of yamin)", "category": "sunnah", "habit_type": "binary", "difficulty": "easy",
     "icon": "👉", "target_count": 1, "unit": "day",
     "islamic_source": "Bukhari 168 — The Prophet ﷺ loved to start from the right in all matters",
     "minimum_version": "Enter the masjid with right foot — start with one sunnah",
     "estimated_minutes": 0, "anchor_prayer": None,
     "description": "Begin all actions from the right side as sunnah"},
    {"key": "gratitude_3", "name": "List 3 things I'm grateful for", "category": "personal", "habit_type": "quantity", "difficulty": "easy",
     "icon": "✨", "target_count": 3, "unit": "things",
     "islamic_source": "Ibrahim 14:7 — 'If you are grateful, I will give you more'",
     "minimum_version": "Name 1 specific blessing you noticed today",
     "estimated_minutes": 3, "anchor_prayer": "isha",
     "description": "Nightly shukr journaling — 3 specific blessings"},
    {"key": "friday_surah_kahf", "name": "Read Surah Al-Kahf on Friday", "category": "sunnah", "habit_type": "binary", "difficulty": "easy",
     "icon": "📖", "target_count": 1, "unit": "Friday",
     "islamic_source": "Hakim 2/399 — Whoever reads Al-Kahf on Friday is illuminated between two Fridays",
     "minimum_version": "Read just the first 10 ayat — they protect from Dajjal",
     "estimated_minutes": 20, "anchor_prayer": None,
     "description": "Weekly recitation of Surah Al-Kahf on Jumu'ah"},
    {"key": "family_time", "name": "Dedicated family time daily", "category": "family", "habit_type": "duration", "difficulty": "easy",
     "icon": "👨‍👩‍👧", "target_count": 30, "unit": "minutes",
     "islamic_source": "Tirmidhi 1924 — 'The best of you is the best to his family'",
     "minimum_version": "Eat one meal together with no phones",
     "estimated_minutes": 30, "anchor_prayer": "maghrib",
     "description": "Present, engaged family time every day"},
    {"key": "avoid_haraam_food", "name": "Eat only halal food", "category": "avoid", "habit_type": "avoid", "difficulty": "medium",
     "icon": "✅", "target_count": 0, "unit": "violations",
     "islamic_source": "Quran 2:168 — 'Eat of what is halal and good on earth'",
     "minimum_version": "Check labels for 3 products you regularly use",
     "estimated_minutes": 0, "anchor_prayer": None,
     "description": "Mindful of halal status in all food consumed"},
    {"key": "good_neighbour", "name": "Check on a neighbour weekly", "category": "sadaqah", "habit_type": "binary", "difficulty": "easy",
     "icon": "🏘️", "target_count": 1, "unit": "check-in",
     "islamic_source": "Bukhari 6015 — Jibreel kept reminding about the neighbour until the Prophet ﷺ thought they would inherit",
     "minimum_version": "Send a message or ring doorbell — 2 minutes",
     "estimated_minutes": 10, "anchor_prayer": None,
     "description": "Weekly kindness to neighbours"},
    {"key": "journal_daily", "name": "Daily reflection journal", "category": "personal", "habit_type": "binary", "difficulty": "easy",
     "icon": "✍️", "target_count": 1, "unit": "entry",
     "islamic_source": "Quran 59:18 — 'Let every soul consider what it has sent forth for tomorrow'",
     "minimum_version": "Write 3 sentences: what happened, how I felt, what I'll do differently",
     "estimated_minutes": 10, "anchor_prayer": "isha",
     "description": "Nightly muhasabah journaling"},
    {"key": "give_salam", "name": "Spread salam generously", "category": "sunnah", "habit_type": "quantity", "difficulty": "easy",
     "icon": "👋", "target_count": 5, "unit": "salams",
     "islamic_source": "Muslim 54 — 'You will not enter Paradise until you believe, and you will not believe until you love each other. Shall I tell you something that will cause you to love one another? Spread salam'",
     "minimum_version": "Say salam to 1 person you wouldn't usually greet",
     "estimated_minutes": 0, "anchor_prayer": None,
     "description": "Proactively spread peace greetings to Muslims"},
]

# ─── Dhikr counter presets ────────────────────────────────────────────────────

DHIKR_PRESETS = [
    {"type": "subhanallah",          "label": "SubhanAllah",           "arabic": "سُبْحَانَ اللَّه", "target": 33},
    {"type": "alhamdulillah",        "label": "Alhamdulillah",         "arabic": "الْحَمْدُ لِلَّه", "target": 33},
    {"type": "allahu_akbar",         "label": "Allahu Akbar",          "arabic": "اللَّهُ أَكْبَر", "target": 34},
    {"type": "la_ilaha_illallah",    "label": "La ilaha illAllah",     "arabic": "لَا إِلَٰهَ إِلَّا اللَّه", "target": 100},
    {"type": "istighfar",            "label": "Astaghfirullah",        "arabic": "أَسْتَغْفِرُ اللَّه", "target": 100},
    {"type": "salawat",              "label": "Salawat",               "arabic": "اللَّهُمَّ صَلِّ عَلَى مُحَمَّد", "target": 100},
    {"type": "subhanallahi_bihamdi", "label": "SubhanAllahi wa bihamdih", "arabic": "سُبْحَانَ اللَّهِ وَبِحَمْدِهِ", "target": 100},
]


async def seed_habit_library(db, user_id=None) -> int:
    """
    Returns the full library as a list of dicts.
    If user_id is provided, creates habits for that user from the library.
    """
    return len(HABIT_LIBRARY)


def get_library_by_category() -> dict:
    cats = {}
    for h in HABIT_LIBRARY:
        cat = h["category"]
        cats.setdefault(cat, []).append(h)
    return cats

# ─── Extended library (additional 65 habits) ─────────────────────────────────

HABIT_LIBRARY_EXTENDED = [
    # ── Salah extras ──────────────────────────────────────────────────────
    {"key": "qiyam_weekend",    "name": "Qiyam al-Layl on weekends", "category": "ibadah", "habit_type": "binary", "difficulty": "hard",
     "icon": "🌙", "target_count": 1, "unit": "session", "islamic_source": "Quran 73:2-4",
     "minimum_version": "2 rakat after waking for water at night", "estimated_minutes": 20, "anchor_prayer": None,
     "description": "Weekend night prayer for extra spiritual connection"},
    {"key": "ishraq_prayer",    "name": "Pray Ishraq (after sunrise)", "category": "ibadah", "habit_type": "binary", "difficulty": "medium",
     "icon": "🌅", "target_count": 1, "unit": "prayer", "islamic_source": "Tirmidhi 586 — Reward of complete Hajj and Umrah",
     "minimum_version": "Stay seated after Fajr dhikr until sunrise, pray 2 rakat", "estimated_minutes": 10, "anchor_prayer": "fajr",
     "description": "2+ rakat prayed 15 min after sunrise"},
    {"key": "salah_khushu",     "name": "Focus completely in one salah", "category": "ibadah", "habit_type": "binary", "difficulty": "epic",
     "icon": "🧘", "target_count": 1, "unit": "prayer", "islamic_source": "Quran 23:1-2 — 'Successful are those who have khushu in prayer'",
     "minimum_version": "Turn off notifications and face a blank wall for one prayer", "estimated_minutes": 10, "anchor_prayer": None,
     "description": "Intentional focus practice in at least one daily salah"},

    # ── Quran extras ───────────────────────────────────────────────────────
    {"key": "quran_recite_aloud",  "name": "Recite Quran aloud for 10 min", "category": "quran", "habit_type": "duration", "difficulty": "easy",
     "icon": "🔊", "target_count": 10, "unit": "minutes", "islamic_source": "Abu Dawud 1477 — Beautify the Quran with your voice",
     "minimum_version": "Read 3 ayat aloud — voice practice beats silent reading", "estimated_minutes": 10, "anchor_prayer": "fajr",
     "description": "Daily voiced Quran recitation for tajweed and barakah"},
    {"key": "quran_teach_child", "name": "Teach child a Quran verse weekly", "category": "quran", "habit_type": "binary", "difficulty": "easy",
     "icon": "👧", "target_count": 1, "unit": "verse", "islamic_source": "Bukhari 5027 — Best of you teaches Quran",
     "minimum_version": "Read Al-Fatiha together slowly with explanation", "estimated_minutes": 10, "anchor_prayer": None,
     "description": "Pass on Quranic knowledge to children weekly"},
    {"key": "quran_dua_verse",   "name": "Pick a Quranic dua daily", "category": "quran", "habit_type": "binary", "difficulty": "easy",
     "icon": "🤲", "target_count": 1, "unit": "verse", "islamic_source": "Quran 2:286 — 'Our Lord, do not burden us'",
     "minimum_version": "Read one supplication verse from the Quran app", "estimated_minutes": 3, "anchor_prayer": "fajr",
     "description": "Daily Quranic supplication — use Quran itself as your dua"},
    {"key": "quran_meaning",    "name": "Understand meaning of recited verses", "category": "quran", "habit_type": "quantity", "difficulty": "medium",
     "icon": "💡", "target_count": 5, "unit": "verses", "islamic_source": "Quran 47:24 — 'Do they not ponder the Quran?'",
     "minimum_version": "Look up the translation of the verses you prayed today", "estimated_minutes": 10, "anchor_prayer": None,
     "description": "5 verses per day with their meaning studied"},

    # ── Dhikr extras ───────────────────────────────────────────────────────
    {"key": "dhikr_commute",    "name": "Dhikr during commute", "category": "dhikr", "habit_type": "duration", "difficulty": "easy",
     "icon": "🚗", "target_count": 15, "unit": "minutes", "islamic_source": "Quran 33:41-42 — 'Remember Allah with much remembrance'",
     "minimum_version": "Turn off radio and say SubhanAllah for first 5 min of journey", "estimated_minutes": 15, "anchor_prayer": None,
     "description": "Transform commute time into worship"},
    {"key": "tasbeeh_hadiths",  "name": "Learn 1 new tasbeeh with source", "category": "dhikr", "habit_type": "binary", "difficulty": "easy",
     "icon": "📖", "target_count": 1, "unit": "tasbeeh", "islamic_source": "Muslim 2691 — Every tasbeeh has specific rewards",
     "minimum_version": "Look up 1 dhikr phrase and its source today", "estimated_minutes": 5, "anchor_prayer": None,
     "description": "Weekly learning of authenticated adhkar"},
    {"key": "durood_friday_1000","name": "Send salawat 1000× on Friday", "category": "dhikr", "habit_type": "quantity", "difficulty": "hard",
     "icon": "💚", "target_count": 1000, "unit": "times", "islamic_source": "Many scholars recommend abundant salawat on Jumu'ah",
     "minimum_version": "Send salawat 100 times after Jumuah prayer", "estimated_minutes": 30, "anchor_prayer": "dhuhr",
     "description": "Abundant salawat on the Prophet ﷺ every Friday"},

    # ── Health extras ───────────────────────────────────────────────────────
    {"key": "walking_after_meal","name": "Walk 10 min after dinner", "category": "health", "habit_type": "duration", "difficulty": "easy",
     "icon": "🚶", "target_count": 10, "unit": "minutes", "islamic_source": "Sunnah of the Prophet ﷺ — moderate walking after eating",
     "minimum_version": "Walk to the masjid and back for Isha", "estimated_minutes": 10, "anchor_prayer": "maghrib",
     "description": "Post-dinner walk for digestion and Maghrib/Isha connection"},
    {"key": "no_sugar",         "name": "No added sugar today", "category": "avoid", "habit_type": "avoid", "difficulty": "hard",
     "icon": "🚫", "target_count": 0, "unit": "incidents", "islamic_source": "Tirmidhi 2380 — 'A few morsels to keep his back straight'",
     "minimum_version": "Replace sweet tea with water for just one day", "estimated_minutes": 0, "anchor_prayer": None,
     "description": "Eliminate refined sugar as body amanah"},
    {"key": "cold_shower",      "name": "Cold shower morning", "category": "health", "habit_type": "binary", "difficulty": "hard",
     "icon": "🚿", "target_count": 1, "unit": "shower", "islamic_source": "Ghusl regularly is a sunnah; strengthening the body is fard",
     "minimum_version": "End shower with 30 seconds cold — just the last 30s", "estimated_minutes": 5, "anchor_prayer": "fajr",
     "description": "Cold shower for alertness and Fajr energy"},
    {"key": "fruits_daily",     "name": "Eat 3 fruits/vegetables today", "category": "health", "habit_type": "quantity", "difficulty": "easy",
     "icon": "🍎", "target_count": 3, "unit": "portions", "islamic_source": "Sunnah foods from Paradise — pomegranate, grapes, figs",
     "minimum_version": "Add one fruit to breakfast today", "estimated_minutes": 5, "anchor_prayer": None,
     "description": "Daily fruit and vegetable intake for body amanah"},
    {"key": "no_late_screens",  "name": "No screens after 10pm", "category": "avoid", "habit_type": "avoid", "difficulty": "hard",
     "icon": "🌙", "target_count": 0, "unit": "incidents", "islamic_source": "Bukhari 6311 — Prophet ﷺ disliked staying awake after Isha unnecessarily",
     "minimum_version": "Put phone in Do Not Disturb at 10pm — check one last time then put down", "estimated_minutes": 0, "anchor_prayer": "isha",
     "description": "Screen curfew for better sleep and earlier Fajr"},

    # ── Sadaqah extras ──────────────────────────────────────────────────────
    {"key": "volunteer_monthly","name": "Volunteer 1 hour monthly", "category": "sadaqah", "habit_type": "binary", "difficulty": "easy",
     "icon": "🤝", "target_count": 1, "unit": "session", "islamic_source": "Muslim 1631 — Sadaqah extends beyond wealth to time",
     "minimum_version": "Help set up or clean up at your local masjid", "estimated_minutes": 60, "anchor_prayer": None,
     "description": "Monthly community service — time as sadaqah"},
    {"key": "share_knowledge",  "name": "Share Islamic knowledge weekly", "category": "sadaqah", "habit_type": "binary", "difficulty": "easy",
     "icon": "📱", "target_count": 1, "unit": "share", "islamic_source": "Muslim 1631 — Beneficial knowledge that outlives you",
     "minimum_version": "Share 1 authenticated hadith or Quran verse with one person", "estimated_minutes": 5, "anchor_prayer": None,
     "description": "Weekly spread of beneficial Islamic knowledge"},
    {"key": "feed_someone",     "name": "Feed someone this week", "category": "sadaqah", "habit_type": "binary", "difficulty": "easy",
     "icon": "🍱", "target_count": 1, "unit": "meal", "islamic_source": "Bukhari 12 — Feed others as sign of iman",
     "minimum_version": "Bring a dish to share at work or school once a week", "estimated_minutes": 20, "anchor_prayer": None,
     "description": "Weekly act of feeding another person"},
    {"key": "forgive_daily",    "name": "Forgive someone today", "category": "sadaqah", "habit_type": "binary", "difficulty": "epic",
     "icon": "💞", "target_count": 1, "unit": "person", "islamic_source": "Quran 3:134 — 'Those who pardon people — Allah loves the good-doers'",
     "minimum_version": "Think of one person you have a grudge against and make dua for them", "estimated_minutes": 5, "anchor_prayer": None,
     "description": "Daily act of forgiveness — release and dua for the other"},

    # ── Learning extras ─────────────────────────────────────────────────────
    {"key": "fiqh_study",       "name": "Study fiqh of one ruling weekly", "category": "learning", "habit_type": "binary", "difficulty": "medium",
     "icon": "⚖️", "target_count": 1, "unit": "ruling", "islamic_source": "Abu Dawud 3641 — 'Whoever Allah wishes good for, He gives him understanding in the religion'",
     "minimum_version": "Look up the ruling on one everyday action you do", "estimated_minutes": 20, "anchor_prayer": None,
     "description": "Weekly fiqh literacy — know the rulings on your daily life"},
    {"key": "scholar_lecture",  "name": "Listen to scholar lecture weekly", "category": "learning", "habit_type": "binary", "difficulty": "easy",
     "icon": "🎧", "target_count": 1, "unit": "lecture", "islamic_source": "Muslim 2699 — Paths to knowledge lead to Paradise",
     "minimum_version": "Listen to 10 min of a scholar during cooking or driving", "estimated_minutes": 30, "anchor_prayer": None,
     "description": "Weekly lecture from authenticated scholars"},
    {"key": "names_of_allah",   "name": "Learn one Name of Allah weekly", "category": "learning", "habit_type": "binary", "difficulty": "easy",
     "icon": "✨", "target_count": 1, "unit": "name", "islamic_source": "Bukhari 2736 — 'Allah has 99 Names; whoever memorises them enters Paradise'",
     "minimum_version": "Learn one Name, its meaning, and make dua with it today", "estimated_minutes": 10, "anchor_prayer": None,
     "description": "Weekly memorisation of Allah's beautiful Names"},
    {"key": "dawah_monthly",    "name": "Share Islam with non-Muslim monthly", "category": "learning", "habit_type": "binary", "difficulty": "medium",
     "icon": "🌍", "target_count": 1, "unit": "conversation", "islamic_source": "Quran 16:125 — 'Invite to the way of your Lord with wisdom and beautiful advice'",
     "minimum_version": "Simply be an excellent character example to a non-Muslim colleague", "estimated_minutes": 0, "anchor_prayer": None,
     "description": "Monthly gentle dawah by character or conversation"},

    # ── Family & Personal extras ─────────────────────────────────────────────
    {"key": "dua_for_parents",  "name": "Make dua for parents daily", "category": "family", "habit_type": "binary", "difficulty": "easy",
     "icon": "🤲", "target_count": 1, "unit": "dua", "islamic_source": "Quran 17:24 — 'My Lord, have mercy on them as they raised me'",
     "minimum_version": "Add dua for parents to your after-salah dhikr", "estimated_minutes": 1, "anchor_prayer": "isha",
     "description": "Daily dua for parents — alive or deceased"},
    {"key": "quality_spouse",   "name": "Show appreciation to spouse daily", "category": "family", "habit_type": "binary", "difficulty": "easy",
     "icon": "💕", "target_count": 1, "unit": "act", "islamic_source": "Tirmidhi 1162 — 'The best of you is the best to his spouse'",
     "minimum_version": "Say one specific thing you appreciate about your spouse", "estimated_minutes": 5, "anchor_prayer": None,
     "description": "Daily specific appreciation for your spouse"},
    {"key": "avoid_anger",      "name": "Control anger today", "category": "avoid", "habit_type": "avoid", "difficulty": "epic",
     "icon": "😤", "target_count": 0, "unit": "incidents", "islamic_source": "Bukhari 6114 — 'Do not be angry' — repeated 3 times by the Prophet ﷺ",
     "minimum_version": "When angry: sit if standing, make wudu, say A'udhu billah", "estimated_minutes": 0, "anchor_prayer": None,
     "description": "Anger management — applying the Prophetic prescription"},
    {"key": "weekly_planning",  "name": "Plan the week on Sunday night", "category": "personal", "habit_type": "binary", "difficulty": "easy",
     "icon": "📅", "target_count": 1, "unit": "week", "islamic_source": "Quran 59:18 — 'Consider what you have sent forth for tomorrow'",
     "minimum_version": "Write 3 things you want to achieve this week", "estimated_minutes": 15, "anchor_prayer": "isha",
     "description": "Weekly intentional planning from an Islamic lens"},
    {"key": "monthly_account",  "name": "Monthly muhasabah (self-account)", "category": "personal", "habit_type": "binary", "difficulty": "medium",
     "icon": "📊", "target_count": 1, "unit": "session", "islamic_source": "Umar ibn al-Khattab (RA) — 'Account yourselves before you are accounted'",
     "minimum_version": "Answer 3 questions: What did I improve? Where did I fall short? One goal for next month", "estimated_minutes": 30, "anchor_prayer": None,
     "description": "Deep monthly spiritual self-assessment"},

    # ── Sunnah extras ───────────────────────────────────────────────────────
    {"key": "recite_entering_home", "name": "Say dua entering home", "category": "sunnah", "habit_type": "binary", "difficulty": "easy",
     "icon": "🏠", "target_count": 1, "unit": "day", "islamic_source": "Muslim 2018",
     "minimum_version": "Post the dua on your door inside", "estimated_minutes": 0, "anchor_prayer": None,
     "description": "Dua upon entering home — protecting household from Shaytan"},
    {"key": "sunnah_sleep_right","name": "Sleep on right side with dua", "category": "sunnah", "habit_type": "binary", "difficulty": "easy",
     "icon": "😴", "target_count": 1, "unit": "night", "islamic_source": "Bukhari 247 — Sleep on right side saying the sleeping dua",
     "minimum_version": "Turn on right side as you close your eyes", "estimated_minutes": 0, "anchor_prayer": "isha",
     "description": "Sunnah sleeping position and night dua"},
    {"key": "recite_after_adhan","name": "Respond to every adhan", "category": "sunnah", "habit_type": "quantity", "difficulty": "easy",
     "icon": "📢", "target_count": 5, "unit": "adhans", "islamic_source": "Muslim 386 — Repeat after muadhdhin then make dua",
     "minimum_version": "Use app notifications as adhan — pause and repeat it", "estimated_minutes": 2, "anchor_prayer": None,
     "description": "Repeat the adhan and make the dua after"},
    {"key": "visit_sick",       "name": "Visit the sick monthly", "category": "sunnah", "habit_type": "binary", "difficulty": "medium",
     "icon": "🏥", "target_count": 1, "unit": "visit", "islamic_source": "Muslim 2568 — 70,000 angels make dua for those who visit the sick",
     "minimum_version": "Send a voice message checking on a friend who is unwell", "estimated_minutes": 30, "anchor_prayer": None,
     "description": "Monthly care for the sick — fulfilling their Islamic right"},
    {"key": "fast_nabawi",      "name": "Fast like the Prophet ﷺ (eat once)", "category": "sunnah", "habit_type": "binary", "difficulty": "epic",
     "icon": "🌿", "target_count": 1, "unit": "day", "islamic_source": "Tirmidhi 2477 — The Prophet ﷺ fasted most of Sha'ban",
     "minimum_version": "Eat a very light lunch and skip dinner — just one day", "estimated_minutes": 0, "anchor_prayer": None,
     "description": "Prophetic light eating — physical and spiritual purification"},

    # ── Avoid extras ─────────────────────────────────────────────────────────
    {"key": "no_gossip",        "name": "No gossip today", "category": "avoid", "habit_type": "avoid", "difficulty": "hard",
     "icon": "🤐", "target_count": 0, "unit": "incidents", "islamic_source": "Quran 49:11-12 — Prohibition of ridicule and suspicion",
     "minimum_version": "Before speaking about someone: ask 'Is this necessary?'", "estimated_minutes": 0, "anchor_prayer": None,
     "description": "Complete day without gossip or talking about others"},
    {"key": "no_wasteful_spend","name": "No wasteful spending today", "category": "avoid", "habit_type": "avoid", "difficulty": "medium",
     "icon": "💸", "target_count": 0, "unit": "incidents", "islamic_source": "Quran 17:26-27 — 'The wasteful are brothers of Shaytan'",
     "minimum_version": "Pause before any non-essential purchase and wait 24h", "estimated_minutes": 0, "anchor_prayer": None,
     "description": "Financial mindfulness aligned with Islamic moderation"},
    {"key": "no_haraam_music",  "name": "Avoid prohibited entertainment", "category": "avoid", "habit_type": "avoid", "difficulty": "hard",
     "icon": "🚫", "target_count": 0, "unit": "incidents", "islamic_source": "Quran 31:6 — 'Those who purchase idle tales to mislead from the way of Allah'",
     "minimum_version": "Replace with Quran, nasheeds, or Islamic podcasts", "estimated_minutes": 0, "anchor_prayer": None,
     "description": "Replace prohibited entertainment with beneficial alternatives"},
    {"key": "lower_gaze",       "name": "Lower gaze intentionally", "category": "avoid", "habit_type": "avoid", "difficulty": "epic",
     "icon": "👁", "target_count": 0, "unit": "violations", "islamic_source": "Quran 24:30 — 'Tell believing men to lower their gaze'",
     "minimum_version": "Morning intention: 'Today I guard my eyes for Allah'", "estimated_minutes": 0, "anchor_prayer": "fajr",
     "description": "Guarding the gaze — protection of the heart"},
]

# Combine into single library
HABIT_LIBRARY = HABIT_LIBRARY + HABIT_LIBRARY_EXTENDED

_FINAL_BATCH = [
    {"key": "pray_for_ummah",      "name": "Make dua for the Ummah daily", "category": "sadaqah", "habit_type": "binary", "difficulty": "easy",
     "icon": "🌍", "target_count": 1, "unit": "dua", "islamic_source": "Tirmidhi 1844 — Dua for your brother in his absence is accepted",
     "minimum_version": "Add one line for the Ummah to your after-Fajr dua", "estimated_minutes": 2, "anchor_prayer": "fajr", "description": "Daily collective dua for Muslims worldwide"},
    {"key": "zakat_tracker",       "name": "Track nisab monthly", "category": "sadaqah", "habit_type": "binary", "difficulty": "easy",
     "icon": "💰", "target_count": 1, "unit": "check", "islamic_source": "Quran 9:60 — Zakat is one of the 5 pillars",
     "minimum_version": "Check current gold price and your savings once a month", "estimated_minutes": 5, "anchor_prayer": None, "description": "Monthly zakat liability awareness"},
    {"key": "tahara_wudu_always",  "name": "Maintain wudu throughout day", "category": "ibadah", "habit_type": "binary", "difficulty": "medium",
     "icon": "💧", "target_count": 1, "unit": "day", "islamic_source": "Tirmidhi 1237 — Wudu is light; staying in wudu is constant light",
     "minimum_version": "Renew wudu after it breaks — just add it to existing habit", "estimated_minutes": 3, "anchor_prayer": None, "description": "Continuous state of ritual purity"},
    {"key": "sit_for_coffee",      "name": "Eat/drink while seated (Sunnah)", "category": "sunnah", "habit_type": "binary", "difficulty": "easy",
     "icon": "🪑", "target_count": 1, "unit": "day", "islamic_source": "Muslim 2024 — Prophet ﷺ forbade drinking while standing",
     "minimum_version": "Stop and sit before drinking — even water", "estimated_minutes": 0, "anchor_prayer": None, "description": "Sunnah eating and drinking manners"},
    {"key": "masjid_fajr_weekly",  "name": "Pray Fajr at masjid once weekly", "category": "ibadah", "habit_type": "binary", "difficulty": "hard",
     "icon": "🕌", "target_count": 1, "unit": "Friday", "islamic_source": "Bukhari 660 — Fajr and Isha in congregation are most difficult for the hypocrites",
     "minimum_version": "Go to masjid for Fajr on Friday — Jumuah prep day", "estimated_minutes": 20, "anchor_prayer": "fajr", "description": "Weekly Fajr at the masjid for brotherhood and barakah"},
    {"key": "quran_print_mushaf",  "name": "Read from physical mushaf weekly", "category": "quran", "habit_type": "binary", "difficulty": "easy",
     "icon": "📗", "target_count": 1, "unit": "session", "islamic_source": "Looking at the mushaf itself is an act of worship",
     "minimum_version": "Read just 5 minutes from a printed mushaf on Friday", "estimated_minutes": 20, "anchor_prayer": None, "description": "Weekly reading from physical Quran — spiritual presence"},
    {"key": "ramadan_khatam",      "name": "Complete Quran in Ramadan", "category": "quran", "habit_type": "quantity", "difficulty": "epic",
     "icon": "🌙", "target_count": 20, "unit": "pages", "islamic_source": "Jibreel would complete the Quran with the Prophet ﷺ every Ramadan",
     "minimum_version": "Read 4 pages after each prayer in Ramadan = 1 Juz/day", "estimated_minutes": 40, "anchor_prayer": None, "description": "Full Quran khatam during Ramadan"},
    {"key": "adhkar_driving",      "name": "Dhikr during every car journey", "category": "dhikr", "habit_type": "binary", "difficulty": "easy",
     "icon": "🚙", "target_count": 1, "unit": "journey", "islamic_source": "Muslim 2218 — Dua for entering vehicle, SubhanAllah during journey",
     "minimum_version": "Say the car dua before starting the engine — memorise it", "estimated_minutes": 0, "anchor_prayer": None, "description": "Transform every car journey into worship"},
    {"key": "phone_screen_time",   "name": "Less than 2hr screen time daily", "category": "avoid", "habit_type": "avoid", "difficulty": "hard",
     "icon": "📱", "target_count": 0, "unit": "hours excess", "islamic_source": "Tirmidhi 2417 — Free time is a blessing most people waste",
     "minimum_version": "Check screen time in settings — just awareness first", "estimated_minutes": 0, "anchor_prayer": None, "description": "Digital minimalism for spiritual focus"},
    {"key": "think_before_speak",  "name": "Pause 3 seconds before responding", "category": "sunnah", "habit_type": "binary", "difficulty": "medium",
     "icon": "💭", "target_count": 1, "unit": "day", "islamic_source": "Bukhari 6018 — Speak good or be silent",
     "minimum_version": "Count to 3 in your head before any reply in conversation", "estimated_minutes": 0, "anchor_prayer": None, "description": "Prophetic deliberation before speech"},
    {"key": "environment_care",    "name": "Pick up litter once weekly", "category": "sunnah", "habit_type": "binary", "difficulty": "easy",
     "icon": "🌿", "target_count": 1, "unit": "time", "islamic_source": "Muslim 553 — Removing harm from the path is charity",
     "minimum_version": "Pick up one piece of litter you see this week", "estimated_minutes": 2, "anchor_prayer": None, "description": "Environmental stewardship as sadaqah"},
    {"key": "check_halal_status",  "name": "Verify halal status of new products", "category": "avoid", "habit_type": "binary", "difficulty": "easy",
     "icon": "✅", "target_count": 1, "unit": "check", "islamic_source": "Quran 2:168 — 'Eat of what is halal and good'",
     "minimum_version": "Check one new product's halal status per week", "estimated_minutes": 3, "anchor_prayer": None, "description": "Weekly halal verification for new food products"},
    {"key": "recite_two_salams",   "name": "Complete salams with both shoulders", "category": "ibadah", "habit_type": "binary", "difficulty": "easy",
     "icon": "👋", "target_count": 1, "unit": "day", "islamic_source": "Abu Dawud — Full salam from both sides completes the prayer",
     "minimum_version": "After each salam, rest in tashahhud position before getting up", "estimated_minutes": 0, "anchor_prayer": None, "description": "Mindful completion of salah tasleem"},
    {"key": "islamic_reminder_group","name": "Share one reminder in family chat", "category": "family", "habit_type": "binary", "difficulty": "easy",
     "icon": "💬", "target_count": 1, "unit": "reminder", "islamic_source": "Muslim 1631 — Beneficial knowledge benefits others after death",
     "minimum_version": "Share one hadith or dua image in your family WhatsApp daily", "estimated_minutes": 3, "anchor_prayer": None, "description": "Spreading beneficial Islamic reminders in family"},
    {"key": "reduce_meat",         "name": "Eat less meat 2 days/week", "category": "health", "habit_type": "quantity", "difficulty": "medium",
     "icon": "🥦", "target_count": 2, "unit": "days", "islamic_source": "The Prophet ﷺ ate meat only occasionally — mostly fruits, vegetables, bread",
     "minimum_version": "Have a vegetarian dinner on Monday", "estimated_minutes": 0, "anchor_prayer": None, "description": "Prophetic diet pattern — occasional meat consumption"},
    {"key": "sunlight_morning",    "name": "Get morning sunlight 10 min", "category": "health", "habit_type": "duration", "difficulty": "easy",
     "icon": "☀️", "target_count": 10, "unit": "minutes", "islamic_source": "Sunnah of prayer in open — the Prophet ﷺ prayed outdoors often",
     "minimum_version": "Stand outside after Fajr for your dhikr — 5 minutes only", "estimated_minutes": 10, "anchor_prayer": "fajr", "description": "Morning sunlight for serotonin and vitamin D"},
    {"key": "phone_free_meal",     "name": "Phone-free family meal daily", "category": "family", "habit_type": "binary", "difficulty": "medium",
     "icon": "🍽️", "target_count": 1, "unit": "meal", "islamic_source": "The Prophet ﷺ shared meals with his family — full presence",
     "minimum_version": "Put phone face-down on the table during dinner", "estimated_minutes": 20, "anchor_prayer": "maghrib", "description": "Undivided presence during at least one family meal"},
    {"key": "prophetic_swim",      "name": "Swim or archery monthly", "category": "health", "habit_type": "binary", "difficulty": "medium",
     "icon": "🏊", "target_count": 1, "unit": "session", "islamic_source": "The Prophet ﷺ recommended swimming, archery, and horse-riding",
     "minimum_version": "Book a pool session once this month", "estimated_minutes": 60, "anchor_prayer": None, "description": "Monthly prophetically-recommended physical activity"},
    {"key": "tawakkul_worry",      "name": "Release one worry to Allah daily", "category": "personal", "habit_type": "binary", "difficulty": "medium",
     "icon": "🕊️", "target_count": 1, "unit": "worry", "islamic_source": "Quran 3:160 — 'If Allah helps you, none can overcome you'",
     "minimum_version": "Write one worry, then write 'Ya Allah, I entrust this to You'", "estimated_minutes": 5, "anchor_prayer": "isha", "description": "Daily tawakkul practice — intentional worry release"},
    {"key": "purify_income",       "name": "Review income sources for riba monthly", "category": "avoid", "habit_type": "binary", "difficulty": "medium",
     "icon": "💼", "target_count": 1, "unit": "review", "islamic_source": "Quran 2:275 — 'Allah has permitted trade and forbidden riba'",
     "minimum_version": "Check one financial product you use for interest involvement", "estimated_minutes": 10, "anchor_prayer": None, "description": "Monthly halal income audit"},
    {"key": "make_wudu_angry",     "name": "Make wudu when angry", "category": "sunnah", "habit_type": "binary", "difficulty": "medium",
     "icon": "💧", "target_count": 1, "unit": "incident", "islamic_source": "Abu Dawud 4784 — 'Anger comes from Shaytan, and Shaytan from fire — extinguish it with water'",
     "minimum_version": "Post reminder: 'Angry? → Wudu' on your bathroom mirror", "estimated_minutes": 3, "anchor_prayer": None, "description": "Prophetic anger management via wudu"},
    {"key": "one_sunnah_today",    "name": "Revive one forgotten Sunnah weekly", "category": "sunnah", "habit_type": "binary", "difficulty": "easy",
     "icon": "🌟", "target_count": 1, "unit": "sunnah", "islamic_source": "Tirmidhi 2678 — Reviving a forgotten sunnah = 100 martyrs' reward",
     "minimum_version": "Search 'forgotten sunnah' and pick one to implement this week", "estimated_minutes": 5, "anchor_prayer": None, "description": "Weekly revival of a neglected Prophetic practice"},
    {"key": "smile_sunnah",        "name": "Smile at every Muslim today", "category": "sunnah", "habit_type": "binary", "difficulty": "easy",
     "icon": "😊", "target_count": 1, "unit": "day", "islamic_source": "Tirmidhi 1956 — 'Smiling at your brother is charity'",
     "minimum_version": "Make eye contact and smile at 3 Muslims today", "estimated_minutes": 0, "anchor_prayer": None, "description": "The Prophet's ﷺ most constant sunnah — the smile"},
    {"key": "no_complain",         "name": "No complaining today", "category": "avoid", "habit_type": "avoid", "difficulty": "hard",
     "icon": "🤐", "target_count": 0, "unit": "complaints", "islamic_source": "Quran 2:155-157 — 'Give glad tidings to the patient'",
     "minimum_version": "Replace one complaint with 'Alhamdulillah' today", "estimated_minutes": 0, "anchor_prayer": None, "description": "Sabr in action — complete day without voicing complaints"},
    {"key": "memorise_dua_istikhara","name": "Memorise Dua Istikhara", "category": "learning", "habit_type": "binary", "difficulty": "medium",
     "icon": "🤲", "target_count": 1, "unit": "memorised", "islamic_source": "Bukhari 6382 — Teach Istikhara like you teach Surahs of Quran",
     "minimum_version": "Read it 5 times today from memory practice", "estimated_minutes": 10, "anchor_prayer": None, "description": "One-time goal: memorise the Istikhara dua completely"},
    {"key": "charity_box_home",    "name": "Put coin in home charity box daily", "category": "sadaqah", "habit_type": "binary", "difficulty": "easy",
     "icon": "🏦", "target_count": 1, "unit": "coin", "islamic_source": "Bukhari 1421 — Give sadaqah daily even if very little",
     "minimum_version": "Place a jar in your kitchen — drop in any coin daily", "estimated_minutes": 0, "anchor_prayer": "fajr", "description": "Daily micro-sadaqah habit — small and consistent"},
]

HABIT_LIBRARY = HABIT_LIBRARY + _FINAL_BATCH
