"""phase4_habits

Revision ID: 001f167c4da0
Revises: 0e8dab9bee04
Create Date: 2026-04-14 15:09:48.995942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001f167c4da0'
down_revision: Union[str, None] = '0e8dab9bee04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dhikr_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('dhikr_type', sa.Enum('SUBHANALLAH', 'ALHAMDULILLAH', 'ALLAHU_AKBAR', 'LA_ILAHA_ILLALLAH', 'ISTIGHFAR', 'SALAWAT', 'SUBHANALLAHI_BIHAMDI', 'CUSTOM', name='dhikrtype'), nullable=False),
    sa.Column('custom_label', sa.String(length=200), nullable=True),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('current_count', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dhikr_sessions_session_date'), 'dhikr_sessions', ['session_date'], unique=False)
    op.create_index(op.f('ix_dhikr_sessions_user_id'), 'dhikr_sessions', ['user_id'], unique=False)
    op.create_table('habit_checklist_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('habit_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('arabic_text', sa.String(length=500), nullable=True),
    sa.Column('repetition_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habit_checklist_items_habit_id'), 'habit_checklist_items', ['habit_id'], unique=False)
    op.create_table('habit_checklist_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['habit_checklist_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'log_date', name='uq_checklist_log')
    )
    op.create_index(op.f('ix_habit_checklist_logs_item_id'), 'habit_checklist_logs', ['item_id'], unique=False)
    
    op.execute("CREATE TYPE habittype AS ENUM ('BINARY', 'QUANTITY', 'DURATION', 'AVOID', 'CHECKLIST')")
    op.execute("CREATE TYPE habitdifficulty AS ENUM ('EASY', 'MEDIUM', 'HARD', 'EPIC')")
    op.execute("CREATE TYPE anchorprayer AS ENUM ('FAJR', 'DHUHR', 'ASR', 'MAGHRIB', 'ISHA')")

    op.add_column('habits', sa.Column('habit_type', sa.Enum('BINARY', 'QUANTITY', 'DURATION', 'AVOID', 'CHECKLIST', name='habittype'), nullable=False))
    op.add_column('habits', sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', 'EPIC', name='habitdifficulty'), nullable=False))
    op.add_column('habits', sa.Column('implementation_intention', sa.String(length=500), nullable=True))
    op.add_column('habits', sa.Column('habit_stack_order', sa.Integer(), nullable=False))
    op.add_column('habits', sa.Column('temptation_bundle', sa.String(length=500), nullable=True))
    op.add_column('habits', sa.Column('current_streak', sa.Integer(), nullable=False))
    op.add_column('habits', sa.Column('longest_streak', sa.Integer(), nullable=False))
    op.add_column('habits', sa.Column('total_completions', sa.Integer(), nullable=False))
    op.add_column('habits', sa.Column('is_preset', sa.Boolean(), nullable=False))
    op.add_column('habits', sa.Column('islamic_source', sa.String(length=500), nullable=True))
    op.add_column('habits', sa.Column('minimum_version', sa.String(length=500), nullable=True))
    op.add_column('habits', sa.Column('anchor_prayer', sa.Enum('FAJR', 'DHUHR', 'ASR', 'MAGHRIB', 'ISHA', name='anchorprayer'), nullable=True))
    op.add_column('habits', sa.Column('rahmah_tokens', sa.Integer(), nullable=False))
    op.add_column('habits', sa.Column('last_token_earned', sa.Date(), nullable=True))
    op.add_column('tasks', sa.Column('islamic_context', sa.String(length=500), nullable=True))
    op.add_column('tasks', sa.Column('linked_habit_id', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('is_urgent', sa.Boolean(), nullable=False))
    op.add_column('tasks', sa.Column('is_important', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'habits', ['linked_habit_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'is_important')
    op.drop_column('tasks', 'is_urgent')
    op.drop_column('tasks', 'linked_habit_id')
    op.drop_column('tasks', 'islamic_context')
    op.drop_column('habits', 'last_token_earned')
    op.drop_column('habits', 'rahmah_tokens')
    op.drop_column('habits', 'anchor_prayer')
    op.drop_column('habits', 'minimum_version')
    op.drop_column('habits', 'islamic_source')
    op.drop_column('habits', 'is_preset')
    op.drop_column('habits', 'total_completions')
    op.drop_column('habits', 'longest_streak')
    op.drop_column('habits', 'current_streak')
    op.drop_column('habits', 'temptation_bundle')
    op.drop_column('habits', 'habit_stack_order')
    op.drop_column('habits', 'implementation_intention')
    op.drop_column('habits', 'difficulty')
    op.drop_column('habits', 'habit_type')
    op.drop_index(op.f('ix_habit_checklist_logs_item_id'), table_name='habit_checklist_logs')
    op.drop_table('habit_checklist_logs')
    op.drop_index(op.f('ix_habit_checklist_items_habit_id'), table_name='habit_checklist_items')
    op.drop_table('habit_checklist_items')
    op.drop_index(op.f('ix_dhikr_sessions_user_id'), table_name='dhikr_sessions')
    op.drop_index(op.f('ix_dhikr_sessions_session_date'), table_name='dhikr_sessions')
    op.drop_table('dhikr_sessions')

    op.execute("DROP TYPE anchorprayer")
    op.execute("DROP TYPE habitdifficulty")
    op.execute("DROP TYPE habittype")
    # ### end Alembic commands ###
