"""phasse3_quran

Revision ID: 0e8dab9bee04
Revises: 0ab0a33f2849
Create Date: 2026-04-14 13:05:56.480718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e8dab9bee04'
down_revision: Union[str, None] = '0ab0a33f2849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('arabic_text', sa.String(length=2000), nullable=False),
    sa.Column('transliteration', sa.String(length=2000), nullable=True),
    sa.Column('translation', sa.String(length=2000), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('when_to_recite', sa.String(length=500), nullable=True),
    sa.Column('repetition_count', sa.Integer(), nullable=False),
    sa.Column('dua_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duas_category'), 'duas', ['category'], unique=False)
    op.create_index(op.f('ix_duas_key'), 'duas', ['key'], unique=True)
    op.create_table('hadiths',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection', sa.Enum('BUKHARI', 'MUSLIM', 'ABU_DAWUD', 'TIRMIDHI', 'NASAI', 'IBN_MAJAH', 'MUWATTA', 'RIYADH_SALIHIN', name='hadithcollection'), nullable=False),
    sa.Column('book_name', sa.String(length=200), nullable=True),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('hadith_number', sa.String(length=20), nullable=False),
    sa.Column('arabic_text', sa.String(length=5000), nullable=True),
    sa.Column('english_text', sa.String(length=5000), nullable=False),
    sa.Column('narrator_chain', sa.String(length=500), nullable=True),
    sa.Column('grade', sa.Enum('SAHIH', 'HASAN', 'DAIF', 'MAWDU', 'UNKNOWN', name='hadithgrade'), nullable=False),
    sa.Column('grade_note', sa.String(length=500), nullable=True),
    sa.Column('topics', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection', 'hadith_number', name='uq_hadith_ref')
    )
    op.create_index(op.f('ix_hadiths_collection'), 'hadiths', ['collection'], unique=False)
    op.create_table('personal_duas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('text', sa.String(length=3000), nullable=False),
    sa.Column('date_started', sa.Date(), nullable=False),
    sa.Column('is_answered', sa.Boolean(), nullable=False),
    sa.Column('answered_date', sa.Date(), nullable=True),
    sa.Column('answered_note', sa.String(length=1000), nullable=True),
    sa.Column('is_shared_anonymously', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_duas_user_id'), 'personal_duas', ['user_id'], unique=False)
    op.create_table('quran_bookmarks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('surah_number', sa.Integer(), nullable=False),
    sa.Column('ayah_number', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('highlight_color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quran_bookmarks_user_id'), 'quran_bookmarks', ['user_id'], unique=False)
    op.create_table('quran_reading_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('surah_from', sa.Integer(), nullable=False),
    sa.Column('ayah_from', sa.Integer(), nullable=False),
    sa.Column('surah_to', sa.Integer(), nullable=False),
    sa.Column('ayah_to', sa.Integer(), nullable=False),
    sa.Column('verses_read', sa.Integer(), nullable=False),
    sa.Column('minutes_read', sa.Integer(), nullable=False),
    sa.Column('minutes_listened', sa.Integer(), nullable=False),
    sa.Column('reciter_used', sa.String(length=100), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quran_reading_logs_log_date'), 'quran_reading_logs', ['log_date'], unique=False)
    op.create_index(op.f('ix_quran_reading_logs_user_id'), 'quran_reading_logs', ['user_id'], unique=False)
    op.add_column('hifz_progress', sa.Column('leitner_box', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hifz_progress', 'leitner_box')
    op.drop_index(op.f('ix_quran_reading_logs_user_id'), table_name='quran_reading_logs')
    op.drop_index(op.f('ix_quran_reading_logs_log_date'), table_name='quran_reading_logs')
    op.drop_table('quran_reading_logs')
    op.drop_index(op.f('ix_quran_bookmarks_user_id'), table_name='quran_bookmarks')
    op.drop_table('quran_bookmarks')
    op.drop_index(op.f('ix_personal_duas_user_id'), table_name='personal_duas')
    op.drop_table('personal_duas')
    op.drop_index(op.f('ix_hadiths_collection'), table_name='hadiths')
    op.drop_table('hadiths')
    op.drop_index(op.f('ix_duas_key'), table_name='duas')
    op.drop_index(op.f('ix_duas_category'), table_name='duas')
    op.drop_table('duas')
    # ### end Alembic commands ###
