"""init

Revision ID: 239c368a13de
Revises: 
Create Date: 2026-04-09 16:49:08.975341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '239c368a13de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'PREFER_NOT_TO_SAY', name='gender'), nullable=True),
    sa.Column('madhab', sa.Enum('HANAFI', 'SHAFII', 'MALIKI', 'HANBALI', name='madhab'), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('prayer_method', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ai_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('context_module', sa.Enum('GENERAL', 'HABITS', 'QURAN', 'JOURNAL', 'LIFESTYLE', 'HEALTH', name='aicontextmodule'), nullable=False),
    sa.Column('messages', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_user_id'), 'ai_conversations', ['user_id'], unique=False)
    op.create_table('dua_favorites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dua_key', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('custom_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dua_key', name='uq_dua_favorite')
    )
    op.create_index(op.f('ix_dua_favorites_user_id'), 'dua_favorites', ['user_id'], unique=False)
    op.create_table('fasting_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fast_date', sa.Date(), nullable=False),
    sa.Column('fast_type', sa.Enum('RAMADAN', 'QADHA', 'VOLUNTARY', 'SHAWWAL', 'ARAFAH', 'ASHURA', name='fasttype'), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('reason_missed', sa.Enum('HAYD', 'NIFAS', 'ILLNESS', 'TRAVEL', 'FORGOT', 'OTHER', name='missedreason'), nullable=True),
    sa.Column('is_qadha', sa.Boolean(), nullable=False),
    sa.Column('original_fast_date', sa.Date(), nullable=True),
    sa.Column('fidya_applicable', sa.Boolean(), nullable=False),
    sa.Column('fidya_paid', sa.Boolean(), nullable=False),
    sa.Column('kaffarah_applicable', sa.Boolean(), nullable=False),
    sa.Column('kaffarah_completed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fasting_logs_fast_date'), 'fasting_logs', ['fast_date'], unique=False)
    op.create_index(op.f('ix_fasting_logs_user_id'), 'fasting_logs', ['user_id'], unique=False)
    op.create_table('habits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.Enum('IBADAH', 'QURAN', 'DHIKR', 'SUNNAH', 'HEALTH', 'LEARNING', 'PERSONAL', 'FAMILY', 'WORK', name='habitcategory'), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKDAYS', 'WEEKENDS', 'CUSTOM', name='habitfrequency'), nullable=False),
    sa.Column('days_of_week', sa.String(length=20), nullable=True),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habits_user_id'), 'habits', ['user_id'], unique=False)
    op.create_table('hifz_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('surah_number', sa.Integer(), nullable=False),
    sa.Column('surah_name', sa.String(length=100), nullable=True),
    sa.Column('ayah_from', sa.Integer(), nullable=False),
    sa.Column('ayah_to', sa.Integer(), nullable=False),
    sa.Column('total_ayahs', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'MEMORISED', 'NEEDS_REVIEW', name='hifzstatus'), nullable=False),
    sa.Column('last_reviewed', sa.Date(), nullable=True),
    sa.Column('next_review', sa.Date(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'surah_number', 'ayah_from', name='uq_hifz_range')
    )
    op.create_index(op.f('ix_hifz_progress_next_review'), 'hifz_progress', ['next_review'], unique=False)
    op.create_index(op.f('ix_hifz_progress_user_id'), 'hifz_progress', ['user_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('mood', sa.Enum('GRATEFUL', 'PEACEFUL', 'HOPEFUL', 'MOTIVATED', 'REFLECTIVE', 'ANXIOUS', 'SAD', 'OVERWHELMED', 'NEUTRAL', name='mood'), nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('gratitude', sa.Text(), nullable=True),
    sa.Column('intentions', sa.Text(), nullable=True),
    sa.Column('reflection', sa.Text(), nullable=True),
    sa.Column('quran_ayah_ref', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_entry_date'), 'journal_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_journal_entries_user_id'), 'journal_entries', ['user_id'], unique=False)
    op.create_table('menstrual_cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('blood_classification', sa.Enum('HAYD', 'TUHR', 'ISTIHADAH', 'UNCERTAIN', name='bloodclassification'), nullable=False),
    sa.Column('hayd_tuhr_status', sa.Enum('HAYD', 'TUHR', 'ISTIHADAH', name='cyclephase'), nullable=False),
    sa.Column('madhab_ruling', sa.String(length=50), nullable=True),
    sa.Column('can_pray', sa.Boolean(), nullable=False),
    sa.Column('can_fast', sa.Boolean(), nullable=False),
    sa.Column('can_read_quran', sa.Boolean(), nullable=False),
    sa.Column('ghusl_required', sa.Boolean(), nullable=False),
    sa.Column('ghusl_done', sa.Boolean(), nullable=False),
    sa.Column('ghusl_date', sa.Date(), nullable=True),
    sa.Column('cycle_length', sa.Integer(), nullable=True),
    sa.Column('previous_cycle_tuhr_days', sa.Integer(), nullable=True),
    sa.Column('encrypted_notes', sa.LargeBinary(), nullable=True),
    sa.Column('encrypted_symptoms', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menstrual_cycles_start_date'), 'menstrual_cycles', ['start_date'], unique=False)
    op.create_index(op.f('ix_menstrual_cycles_user_id'), 'menstrual_cycles', ['user_id'], unique=False)
    op.create_table('prayer_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('prayer_name', sa.Enum('FAJR', 'DHUHR', 'ASR', 'MAGHRIB', 'ISHA', 'JUMUAH', 'TAHAJJUD', 'DUHA', name='prayername'), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ON_TIME', 'LATE', 'QADHA', 'MISSED', 'EXCUSED', name='prayerstatus'), nullable=False),
    sa.Column('prayed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_qadha', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'prayer_name', 'log_date', name='uq_prayer_per_day')
    )
    op.create_index(op.f('ix_prayer_logs_log_date'), 'prayer_logs', ['log_date'], unique=False)
    op.create_index(op.f('ix_prayer_logs_user_id'), 'prayer_logs', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('WORK', 'PERSONAL', 'IBADAH', 'FAMILY', 'HEALTH', 'LEARNING', 'ERRAND', name='taskcategory'), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('time_block', sa.String(length=50), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_task_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('quran_daily_goal_minutes', sa.Integer(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('prayer_notifications', sa.Boolean(), nullable=False),
    sa.Column('habit_reminder_time', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('habit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('habit_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'log_date', name='uq_habit_log_per_day')
    )
    op.create_index(op.f('ix_habit_logs_habit_id'), 'habit_logs', ['habit_id'], unique=False)
    op.create_index(op.f('ix_habit_logs_log_date'), 'habit_logs', ['log_date'], unique=False)
    op.create_index(op.f('ix_habit_logs_user_id'), 'habit_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_habit_logs_user_id'), table_name='habit_logs')
    op.drop_index(op.f('ix_habit_logs_log_date'), table_name='habit_logs')
    op.drop_index(op.f('ix_habit_logs_habit_id'), table_name='habit_logs')
    op.drop_table('habit_logs')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_prayer_logs_user_id'), table_name='prayer_logs')
    op.drop_index(op.f('ix_prayer_logs_log_date'), table_name='prayer_logs')
    op.drop_table('prayer_logs')
    op.drop_index(op.f('ix_menstrual_cycles_user_id'), table_name='menstrual_cycles')
    op.drop_index(op.f('ix_menstrual_cycles_start_date'), table_name='menstrual_cycles')
    op.drop_table('menstrual_cycles')
    op.drop_index(op.f('ix_journal_entries_user_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_entry_date'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_hifz_progress_user_id'), table_name='hifz_progress')
    op.drop_index(op.f('ix_hifz_progress_next_review'), table_name='hifz_progress')
    op.drop_table('hifz_progress')
    op.drop_index(op.f('ix_habits_user_id'), table_name='habits')
    op.drop_table('habits')
    op.drop_index(op.f('ix_fasting_logs_user_id'), table_name='fasting_logs')
    op.drop_index(op.f('ix_fasting_logs_fast_date'), table_name='fasting_logs')
    op.drop_table('fasting_logs')
    op.drop_index(op.f('ix_dua_favorites_user_id'), table_name='dua_favorites')
    op.drop_table('dua_favorites')
    op.drop_index(op.f('ix_ai_conversations_user_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
