"""phase10_admin_check

Revision ID: 5af12ab19050
Revises: 7dddea7a4d77
Create Date: 2026-04-16 11:20:04.942128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5af12ab19050'
down_revision: Union[str, None] = '7dddea7a4d77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Add the column as nullable first to avoid constraints crashing on existing rows
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=True))
    
    # 2. Populate default values for all existing rows
    op.execute("UPDATE users SET role = 'user' WHERE role IS NULL")
    
    # 3. Alter the column to enforce the NOT NULL constraint going forward
    op.alter_column('users', 'role', nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###

