"""Phase 6 and 8: Scholar QA, Circles, Halaqah, Finance, Family

Revision ID: 7dddea7a4d77
Revises: 06c404963226
Create Date: 2026-04-15 10:57:51.466717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7dddea7a4d77'
down_revision: Union[str, None] = '06c404963226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accountability_circles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('check_in_day', sa.Integer(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vetted_charities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('causes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_zakat_eligible', sa.Boolean(), nullable=False),
    sa.Column('stripe_account', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('circle_goals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('circle_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['circle_id'], ['accountability_circles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circle_goals_circle_id'), 'circle_goals', ['circle_id'], unique=False)
    op.create_table('circle_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('circle_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['circle_id'], ['accountability_circles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('circle_id', 'user_id')
    )
    op.create_index(op.f('ix_circle_members_circle_id'), 'circle_members', ['circle_id'], unique=False)
    op.create_index(op.f('ix_circle_members_user_id'), 'circle_members', ['user_id'], unique=False)
    op.create_table('family_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_user_id', sa.UUID(), nullable=False),
    sa.Column('plan_type', sa.String(length=50), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_plans_admin_user_id'), 'family_plans', ['admin_user_id'], unique=True)
    op.create_table('halaqahs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('h_type', sa.String(length=50), nullable=False),
    sa.Column('curriculum', sa.Text(), nullable=True),
    sa.Column('moderator_id', sa.UUID(), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_halaqahs_moderator_id'), 'halaqahs', ['moderator_id'], unique=False)
    op.create_table('qa_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('madhab_relevance', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_questions_user_id'), 'qa_questions', ['user_id'], unique=False)
    op.create_table('scholar_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('qualifications', sa.Text(), nullable=True),
    sa.Column('institution', sa.String(length=200), nullable=True),
    sa.Column('madhab', sa.String(length=50), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholar_profiles_user_id'), 'scholar_profiles', ['user_id'], unique=True)
    op.create_table('zakat_calculations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('calculation_date', sa.Date(), nullable=False),
    sa.Column('hijri_year', sa.String(length=20), nullable=True),
    sa.Column('nisab_standard', sa.String(length=20), nullable=False),
    sa.Column('assets', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('liabilities', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('net_zakatable_assets', sa.Float(), nullable=False),
    sa.Column('zakat_due', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zakat_calculations_user_id'), 'zakat_calculations', ['user_id'], unique=False)
    op.create_table('zakat_reminders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hawl_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zakat_reminders_user_id'), 'zakat_reminders', ['user_id'], unique=False)
    op.create_table('circle_check_ins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['circle_goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circle_check_ins_goal_id'), 'circle_check_ins', ['goal_id'], unique=False)
    op.create_index(op.f('ix_circle_check_ins_user_id'), 'circle_check_ins', ['user_id'], unique=False)
    op.create_table('family_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['family_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_members_family_id'), 'family_members', ['family_id'], unique=False)
    op.create_index(op.f('ix_family_members_user_id'), 'family_members', ['user_id'], unique=True)
    op.create_table('halaqah_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('halaqah_id', sa.Uuid(), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['halaqah_id'], ['halaqahs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_halaqah_sessions_halaqah_id'), 'halaqah_sessions', ['halaqah_id'], unique=False)
    op.create_table('qa_answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('scholar_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('madhab_note', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['qa_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scholar_id'], ['scholar_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_answers_question_id'), 'qa_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_qa_answers_scholar_id'), 'qa_answers', ['scholar_id'], unique=False)
    op.create_table('halaqah_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['halaqah_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_halaqah_notes_session_id'), 'halaqah_notes', ['session_id'], unique=False)
    op.create_index(op.f('ix_halaqah_notes_user_id'), 'halaqah_notes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_halaqah_notes_user_id'), table_name='halaqah_notes')
    op.drop_index(op.f('ix_halaqah_notes_session_id'), table_name='halaqah_notes')
    op.drop_table('halaqah_notes')
    op.drop_index(op.f('ix_qa_answers_scholar_id'), table_name='qa_answers')
    op.drop_index(op.f('ix_qa_answers_question_id'), table_name='qa_answers')
    op.drop_table('qa_answers')
    op.drop_index(op.f('ix_halaqah_sessions_halaqah_id'), table_name='halaqah_sessions')
    op.drop_table('halaqah_sessions')
    op.drop_index(op.f('ix_family_members_user_id'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_family_id'), table_name='family_members')
    op.drop_table('family_members')
    op.drop_index(op.f('ix_circle_check_ins_user_id'), table_name='circle_check_ins')
    op.drop_index(op.f('ix_circle_check_ins_goal_id'), table_name='circle_check_ins')
    op.drop_table('circle_check_ins')
    op.drop_index(op.f('ix_zakat_reminders_user_id'), table_name='zakat_reminders')
    op.drop_table('zakat_reminders')
    op.drop_index(op.f('ix_zakat_calculations_user_id'), table_name='zakat_calculations')
    op.drop_table('zakat_calculations')
    op.drop_index(op.f('ix_scholar_profiles_user_id'), table_name='scholar_profiles')
    op.drop_table('scholar_profiles')
    op.drop_index(op.f('ix_qa_questions_user_id'), table_name='qa_questions')
    op.drop_table('qa_questions')
    op.drop_index(op.f('ix_halaqahs_moderator_id'), table_name='halaqahs')
    op.drop_table('halaqahs')
    op.drop_index(op.f('ix_family_plans_admin_user_id'), table_name='family_plans')
    op.drop_table('family_plans')
    op.drop_index(op.f('ix_circle_members_user_id'), table_name='circle_members')
    op.drop_index(op.f('ix_circle_members_circle_id'), table_name='circle_members')
    op.drop_table('circle_members')
    op.drop_index(op.f('ix_circle_goals_circle_id'), table_name='circle_goals')
    op.drop_table('circle_goals')
    op.drop_table('vetted_charities')
    op.drop_table('topics')
    op.drop_table('accountability_circles')
    # ### end Alembic commands ###
