"""add_device_id_to_refresh_tokens

Revision ID: a36153375dd8
Revises: d7e8f9a0b1c2
Create Date: 2026-04-29 08:52:34.141012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a36153375dd8'
down_revision: Union[str, None] = 'd7e8f9a0b1c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_push_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('push_token', sa.String(length=512), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_push_tokens_device_id'), 'device_push_tokens', ['device_id'], unique=True)
    op.create_index(op.f('ix_device_push_tokens_user_id'), 'device_push_tokens', ['user_id'], unique=False)
    op.alter_column('child_activity_logs', 'logged_by',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'parent'::character varying"))
    op.drop_index('ix_child_activity_logs_log_date', table_name='child_activity_logs')
    op.create_index(op.f('ix_child_activity_logs_user_id'), 'child_activity_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_child_badges_user_id'), 'child_badges', ['user_id'], unique=False)
    op.alter_column('child_story_progress', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint('quran_last_read_user_id_key', 'quran_last_read', type_='unique')
    op.drop_index('ix_quran_last_read_user_id', table_name='quran_last_read')
    op.create_index(op.f('ix_quran_last_read_user_id'), 'quran_last_read', ['user_id'], unique=True)
    op.add_column('refresh_tokens', sa.Column('device_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_refresh_tokens_device_id'), 'refresh_tokens', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_device_id'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'device_id')
    op.drop_index(op.f('ix_quran_last_read_user_id'), table_name='quran_last_read')
    op.create_index('ix_quran_last_read_user_id', 'quran_last_read', ['user_id'], unique=False)
    op.create_unique_constraint('quran_last_read_user_id_key', 'quran_last_read', ['user_id'])
    op.alter_column('child_story_progress', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_child_badges_user_id'), table_name='child_badges')
    op.drop_index(op.f('ix_child_activity_logs_user_id'), table_name='child_activity_logs')
    op.create_index('ix_child_activity_logs_log_date', 'child_activity_logs', ['log_date'], unique=False)
    op.alter_column('child_activity_logs', 'logged_by',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'parent'::character varying"))
    op.drop_index(op.f('ix_device_push_tokens_user_id'), table_name='device_push_tokens')
    op.drop_index(op.f('ix_device_push_tokens_device_id'), table_name='device_push_tokens')
    op.drop_table('device_push_tokens')
    # ### end Alembic commands ###
