"""phase5_journal_insights

Revision ID: b0de3f62bbaa
Revises: 001f167c4da0
Create Date: 2026-04-14 15:55:38.264792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0de3f62bbaa'
down_revision: Union[str, None] = '001f167c4da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('insight_text', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('PRAYER_PATTERNS', 'QURAN_PATTERNS', 'HABIT_CORRELATIONS', 'SPIRITUAL_TRENDS', 'MOOD_JOURNAL', name='insightcategory'), nullable=False),
    sa.Column('relevant_ayah', sa.String(length=500), nullable=True),
    sa.Column('relevant_hadith', sa.String(length=500), nullable=True),
    sa.Column('generated_at', sa.Date(), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('user_rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_insights_generated_at'), 'daily_insights', ['generated_at'], unique=False)
    op.create_index(op.f('ix_daily_insights_user_id'), 'daily_insights', ['user_id'], unique=False)
    op.create_table('monthly_letters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('letter_text', sa.Text(), nullable=False),
    sa.Column('mood_summary', sa.String(length=200), nullable=True),
    sa.Column('top_themes', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_letters_user_id'), 'monthly_letters', ['user_id'], unique=False)
    
    # Create ENUM type for PostgreSQL before adding the column
    op.execute("CREATE TYPE journalmode AS ENUM ('FREE_WRITE', 'GUIDED_REFLECTION', 'MUHASABAH', 'WEEKLY_REVIEW', 'GRATITUDE')")
    
    op.add_column('journal_entries', sa.Column('journal_mode', sa.Enum('FREE_WRITE', 'GUIDED_REFLECTION', 'MUHASABAH', 'WEEKLY_REVIEW', 'GRATITUDE', name='journalmode'), nullable=True))
    op.add_column('journal_entries', sa.Column('muhasabah_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('journal_entries', sa.Column('gratitude_items', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('journal_entries', sa.Column('weekly_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('journal_entries', sa.Column('ai_prompt_used', sa.String(length=500), nullable=True))
    op.add_column('journal_entries', sa.Column('is_encrypted', sa.Boolean(), nullable=False))
    op.add_column('journal_entries', sa.Column('iv', sa.String(length=100), nullable=True))
    op.add_column('journal_entries', sa.Column('salt', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal_entries', 'salt')
    op.drop_column('journal_entries', 'iv')
    op.drop_column('journal_entries', 'is_encrypted')
    op.drop_column('journal_entries', 'ai_prompt_used')
    op.drop_column('journal_entries', 'weekly_data')
    op.drop_column('journal_entries', 'gratitude_items')
    op.drop_column('journal_entries', 'muhasabah_data')
    op.drop_column('journal_entries', 'journal_mode')
    op.drop_index(op.f('ix_monthly_letters_user_id'), table_name='monthly_letters')
    op.drop_table('monthly_letters')
    op.drop_index(op.f('ix_daily_insights_user_id'), table_name='daily_insights')
    op.drop_index(op.f('ix_daily_insights_generated_at'), table_name='daily_insights')
    op.drop_table('daily_insights')
    
    # Drop ENUM type
    op.execute("DROP TYPE journalmode")
    # ### end Alembic commands ###
