"""Phase 1 : Profile fields

Revision ID: 6a98149157a1
Revises: 373b5f22de25
Create Date: 2026-04-13 09:54:30.669972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a98149157a1'
down_revision: Union[str, None] = '373b5f22de25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('spiritual_archetype', sa.String(length=30), nullable=True))
    op.add_column('user_profiles', sa.Column('preferred_language', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'preferred_language')
    op.drop_column('user_profiles', 'spiritual_archetype')
    op.drop_column('user_profiles', 'country')
    op.drop_column('user_profiles', 'city')
    # ### end Alembic commands ###
